# Builds docker image and pushes tags to image repository
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: "repository-build-image"
    args: ["build", "-t", "us.gcr.io/docai-neuron/tensorio-models/repository", "-f", "dockerfiles/Dockerfile.repository", "."]
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: "repository-apply-tag"
    args: ["tag", "us.gcr.io/docai-neuron/tensorio-models/repository:latest", "us.gcr.io/docai-neuron/tensorio-models/repository:sha-$SHORT_SHA"]
    waitFor:
      - "repository-build-image"
  - name: 'gcr.io/cloud-builders/docker'
    id: "repository-push"
    args: ["push", "us.gcr.io/docai-neuron/tensorio-models/repository"]
    waitFor:
      - "repository-apply-tag"
  - name: 'gcr.io/cloud-builders/docker'
    id: "flea-build-image"
    args: ["build", "-t", "us.gcr.io/docai-neuron/tensorio-models/flea", "-f", "dockerfiles/Dockerfile.flea", "."]
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: "flea-apply-tag"
    args: ["tag", "us.gcr.io/docai-neuron/tensorio-models/flea:latest", "us.gcr.io/docai-neuron/tensorio-models/flea:sha-$SHORT_SHA"]
    waitFor:
      - "flea-build-image"
  - name: 'gcr.io/cloud-builders/docker'
    id: "flea-push"
    args: ["push", "us.gcr.io/docai-neuron/tensorio-models/flea"]
    waitFor:
      - "flea-apply-tag"
  - name: 'gcr.io/cloud-builders/docker'
    id: "aggregator-build-image"
    args: ["build", "-t", "us.gcr.io/docai-neuron/tensorio-models/aggregator", "-f", "aggregator/Dockerfile", "aggregator/"]
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: "aggregator-apply-tag"
    args: ["tag", "us.gcr.io/docai-neuron/tensorio-models/aggregator:latest", "us.gcr.io/docai-neuron/tensorio-models/aggregator:sha-$SHORT_SHA"]
    waitFor:
      - "aggregator-build-image"
  - name: 'gcr.io/cloud-builders/docker'
    id: "aggregator-push"
    args: ["push", "us.gcr.io/docai-neuron/tensorio-models/aggregator"]
    waitFor:
      - "aggregator-apply-tag"
options:
  machineType: N1_HIGHCPU_8
