# Builds docker image and pushes tags to image repository then releases to GKE cluster via Helm.
# Assumes that cluster docker daemon is authorized to pull from image repository.
# Expects the following substitution variables to be defined:
# - _VALUES_FILE : GCS path to values file for helm release
# - _CLOUDSDK_CORE_PROJECT : GCP project in which GKE cluster lives
# - _CLOUDSDK_COMPUTE_ZONE : GCE zone in which GKE cluster lives
# - _CLOUDSDK_CONTAINER_CLUSTER : Name of GKE cluster
# - _RELEASE_NAME : Name for helm release (default: tio-models)
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: "repository-build-image"
    args: ["build", "-t", "us.gcr.io/docai-neuron/tensorio-models/repository", "-f", "dockerfiles/Dockerfile.repository", "."]
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: "repository-apply-tag"
    args: ["tag", "us.gcr.io/docai-neuron/tensorio-models/repository:latest", "us.gcr.io/docai-neuron/tensorio-models/repository:sha-$SHORT_SHA"]
    waitFor:
      - "repository-build-image"
  - name: 'gcr.io/cloud-builders/docker'
    id: "repository-push"
    args: ["push", "us.gcr.io/docai-neuron/tensorio-models/repository"]
    waitFor:
      - "repository-apply-tag"
  - name: 'gcr.io/cloud-builders/docker'
    id: "flea-build-image"
    args: ["build", "-t", "us.gcr.io/docai-neuron/tensorio-models/flea", "-f", "dockerfiles/Dockerfile.flea", "."]
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: "flea-apply-tag"
    args: ["tag", "us.gcr.io/docai-neuron/tensorio-models/flea:latest", "us.gcr.io/docai-neuron/tensorio-models/flea:sha-$SHORT_SHA"]
    waitFor:
      - "flea-build-image"
  - name: 'gcr.io/cloud-builders/docker'
    id: "flea-push"
    args: ["push", "us.gcr.io/docai-neuron/tensorio-models/flea"]
    waitFor:
      - "flea-apply-tag"
  - name: 'gcr.io/cloud-builders/docker'
    id: "aggregator-build-image"
    args: ["build", "-t", "us.gcr.io/docai-neuron/tensorio-models/aggregator", "-f", "aggregator/Dockerfile", "aggregator/"]
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: "aggregator-apply-tag"
    args: ["tag", "us.gcr.io/docai-neuron/tensorio-models/aggregator:latest", "us.gcr.io/docai-neuron/tensorio-models/aggregator:sha-$SHORT_SHA"]
    waitFor:
      - "aggregator-build-image"
  - name: 'gcr.io/cloud-builders/docker'
    id: "aggregator-push"
    args: ["push", "us.gcr.io/docai-neuron/tensorio-models/aggregator"]
    waitFor:
      - "aggregator-apply-tag"
  - name: 'gcr.io/cloud-builders/gsutil'
    id: "values-yaml-download"
    args: ['cp', '${_VALUES_FILE}', 'values.yaml']
    waitFor: ['-']
  - name: 'gcr.io/docai-neuron/helm'
    id: "helm-release"
    env:
      - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
    args:
      - 'upgrade'
      - '--install'
      - '--set'
      - 'deployment.tag=sha-$SHORT_SHA'
      - '-f'
      - 'values.yaml'
      - '${_RELEASE_NAME}'
      - 'helm/'
    waitFor:
      - "repository-push"
      - "flea-push"
      - "aggregator-push"
      - "values-yaml-download"
substitutions:
  _RELEASE_NAME: tio-models
options:
  machineType: N1_HIGHCPU_8
