{{- range .Values.checkSecrets }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-preinstall-check-secrets-{{ .name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    {{- if $.Release.IsUpgrade }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end  }}
    {{ if $.Release.IsInstall }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{ end  }}
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: "Never"
      containers:
        {{- range .keys }}
        - name: check-secret-{{ .displayName }}
          image: "alpine:3.9"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: secret-under-test
              mountPath: /etc/secret
          command: ["stat", "/etc/secret/{{ .key }}"]
        {{- end }}
      volumes:
        - name: secret-under-test
          secret:
            secretName: {{ .name }}
{{- end }}
