{{- if .Values.repository }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-repository
  labels:
    app.kubernetes.io/name: {{ include "tensorio-models.name" . }}-repository
    helm.sh/chart: {{ include "tensorio-models.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-repository
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.repository.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tensorio-models.name" . }}-repository
      app.kubernetes.io/instance: {{ .Release.Name }}-repository
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tensorio-models.name" . }}-repository
        app.kubernetes.io/instance: {{ .Release.Name }}-repository
    spec:
      containers:
        - name: repository
          image: "{{ .Values.repository.deployment.repository }}:{{ .Values.repository.deployment.tag }}"
          imagePullPolicy: {{ .Values.repository.deployment.pullPolicy }}
          volumeMounts:
            {{- if .Values.repository.deployment.serviceAccount }}
            - name: sacred
              mountPath: {{ .Values.repository.deployment.serviceAccount.mountPath }}
            {{- end }}
          env:
            - name: BACKEND
              value: {{ .Values.repository.deployment.backend }}
            {{- if .Values.repository.deployment.repositoryGcsBucket }}
            - name: REPOSITORY_GCS_BUCKET
              value: {{ .Values.repository.deployment.repositoryGcsBucket }}
            {{- end }}
            {{- if .Values.repository.deployment.serviceAccount }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "{{ .Values.repository.deployment.serviceAccount.mountPath }}/{{ .Values.repository.deployment.serviceAccount.key }}"
            {{- end }}
            {{- if .Values.repository.deployment.authTokensFile }}
            - name: AUTH_TOKENS_FILE
              value: {{ .Values.repository.deployment.authTokensFile }}
            {{- end }}
          args: ["-backend", "$(BACKEND)"]
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
            - name: rest
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/repository/healthz
              port: rest
          readinessProbe:
            httpGet:
              path: /v1/repository/healthz
              port: rest
      volumes:
        {{- if .Values.repository.deployment.serviceAccount }}
        - name: sacred
          secret:
            secretName: {{ .Values.repository.deployment.serviceAccount.secret }}
        {{- end }}
{{- end }}
