{{- if .Values.repository }}
{{- if .Values.repository.release }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "tensorio-models.fullname" . }}-repository
  labels:
    app.kubernetes.io/name: {{ include "tensorio-models.name" . }}-repository
    helm.sh/chart: {{ include "tensorio-models.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-repository
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name: {{ include "tensorio-models.fullname" . }}-repository-rest-mapping
      prefix: /rest/
      host: {{ .Values.repository.service.hostname }}
      timeout_ms: 5000
      service: {{ include "tensorio-models.fullname" . }}-repository.{{ .Values.namespace }}:{{ .Values.repository.service.restPort }}
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name: {{ include "tensorio-models.fullname" . }}-repository-grpc-mapping
      prefix: /grpc/
      host: {{ .Values.repository.service.hostname }}
      timeout_ms: 5000
      service: {{ include "tensorio-models.fullname" . }}-repository.{{ .Values.namespace }}:{{ .Values.repository.service.grpcPort }}

spec:
  type: {{ .Values.repository.service.type }}
  ports:
    - port: {{ .Values.repository.service.restPort }}
      targetPort: rest
      protocol: TCP
      name: rest
    - port: {{ .Values.repository.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "tensorio-models.name" . }}-repository
    app.kubernetes.io/instance: {{ .Release.Name }}-repository
{{- end }}
{{- end }}
