version: '3'
services:
  aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "aggregator"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/access/sacred.json
      - AGGREGATION_CKPTS_FILELIST=${AGGREGATION_CKPTS_FILELIST:-sample-ckpts-filelist.txt}
      - AGGREGATION_TYPE=${AGGREGATION_TYPE:-cma}
      - AGGREGATION_OUTPUT_PATH=${AGGREGATION_OUTPUT_PATH}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/etc/access/sacred.json