// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flea.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartTaskResponse_RequestStatus int32

const (
	StartTaskResponse_UNKNOWN  StartTaskResponse_RequestStatus = 0
	StartTaskResponse_REJECTED StartTaskResponse_RequestStatus = 1
	StartTaskResponse_APPROVED StartTaskResponse_RequestStatus = 2
)

var StartTaskResponse_RequestStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "REJECTED",
	2: "APPROVED",
}

var StartTaskResponse_RequestStatus_value = map[string]int32{
	"UNKNOWN":  0,
	"REJECTED": 1,
	"APPROVED": 2,
}

func (x StartTaskResponse_RequestStatus) String() string {
	return proto.EnumName(StartTaskResponse_RequestStatus_name, int32(x))
}

func (StartTaskResponse_RequestStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{7, 0}
}

type FinishTaskRequest_TaskStatus int32

const (
	FinishTaskRequest_UNKNOWN   FinishTaskRequest_TaskStatus = 0
	FinishTaskRequest_COMPLETED FinishTaskRequest_TaskStatus = 1
	FinishTaskRequest_ERROR     FinishTaskRequest_TaskStatus = 2
	FinishTaskRequest_ABORTED   FinishTaskRequest_TaskStatus = 3
)

var FinishTaskRequest_TaskStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "COMPLETED",
	2: "ERROR",
	3: "ABORTED",
}

var FinishTaskRequest_TaskStatus_value = map[string]int32{
	"UNKNOWN":   0,
	"COMPLETED": 1,
	"ERROR":     2,
	"ABORTED":   3,
}

func (x FinishTaskRequest_TaskStatus) String() string {
	return proto.EnumName(FinishTaskRequest_TaskStatus_name, int32(x))
}

func (FinishTaskRequest_TaskStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{8, 0}
}

type CreateTaskRequest struct {
	ModelId           string `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperparametersId string `protobuf:"bytes,2,opt,name=hyperparametersId,proto3" json:"hyperparametersId,omitempty"`
	// Note that TensorIO supports string ChkPtIds, while doc seems to suggest UTC secs-since-epoch.
	// We would also accept updates based on more recent checkpoints.
	CheckpointId         string   `protobuf:"bytes,3,opt,name=checkpointId,proto3" json:"checkpointId,omitempty"`
	TaskId               string   `protobuf:"bytes,4,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Deadline             int64    `protobuf:"varint,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Active               bool     `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	Task                 string   `protobuf:"bytes,7,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskRequest) Reset()         { *m = CreateTaskRequest{} }
func (m *CreateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTaskRequest) ProtoMessage()    {}
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{0}
}

func (m *CreateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskRequest.Unmarshal(m, b)
}
func (m *CreateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskRequest.Marshal(b, m, deterministic)
}
func (m *CreateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskRequest.Merge(m, src)
}
func (m *CreateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTaskRequest.Size(m)
}
func (m *CreateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskRequest proto.InternalMessageInfo

func (m *CreateTaskRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *CreateTaskRequest) GetHyperparametersId() string {
	if m != nil {
		return m.HyperparametersId
	}
	return ""
}

func (m *CreateTaskRequest) GetCheckpointId() string {
	if m != nil {
		return m.CheckpointId
	}
	return ""
}

func (m *CreateTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *CreateTaskRequest) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *CreateTaskRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *CreateTaskRequest) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

type ModifyTaskRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Deadline             int64    `protobuf:"varint,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyTaskRequest) Reset()         { *m = ModifyTaskRequest{} }
func (m *ModifyTaskRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyTaskRequest) ProtoMessage()    {}
func (*ModifyTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{1}
}

func (m *ModifyTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyTaskRequest.Unmarshal(m, b)
}
func (m *ModifyTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyTaskRequest.Marshal(b, m, deterministic)
}
func (m *ModifyTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyTaskRequest.Merge(m, src)
}
func (m *ModifyTaskRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyTaskRequest.Size(m)
}
func (m *ModifyTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyTaskRequest proto.InternalMessageInfo

func (m *ModifyTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *ModifyTaskRequest) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *ModifyTaskRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type ListTasksRequest struct {
	ModelId           string `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperparametersId string `protobuf:"bytes,2,opt,name=hyperparametersId,proto3" json:"hyperparametersId,omitempty"`
	CheckpointId      string `protobuf:"bytes,3,opt,name=checkpointId,proto3" json:"checkpointId,omitempty"`
	// Tasks are returned lexicographically sorted by taskId
	// If specified only taskIds >= startTaskId will be returned.
	StartTaskId          string   `protobuf:"bytes,4,opt,name=startTaskId,proto3" json:"startTaskId,omitempty"`
	MaxItems             int32    `protobuf:"varint,5,opt,name=maxItems,proto3" json:"maxItems,omitempty"`
	ActiveOnly           bool     `protobuf:"varint,6,opt,name=activeOnly,proto3" json:"activeOnly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksRequest) Reset()         { *m = ListTasksRequest{} }
func (m *ListTasksRequest) String() string { return proto.CompactTextString(m) }
func (*ListTasksRequest) ProtoMessage()    {}
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{2}
}

func (m *ListTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksRequest.Unmarshal(m, b)
}
func (m *ListTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksRequest.Marshal(b, m, deterministic)
}
func (m *ListTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksRequest.Merge(m, src)
}
func (m *ListTasksRequest) XXX_Size() int {
	return xxx_messageInfo_ListTasksRequest.Size(m)
}
func (m *ListTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksRequest proto.InternalMessageInfo

func (m *ListTasksRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *ListTasksRequest) GetHyperparametersId() string {
	if m != nil {
		return m.HyperparametersId
	}
	return ""
}

func (m *ListTasksRequest) GetCheckpointId() string {
	if m != nil {
		return m.CheckpointId
	}
	return ""
}

func (m *ListTasksRequest) GetStartTaskId() string {
	if m != nil {
		return m.StartTaskId
	}
	return ""
}

func (m *ListTasksRequest) GetMaxItems() int32 {
	if m != nil {
		return m.MaxItems
	}
	return 0
}

func (m *ListTasksRequest) GetActiveOnly() bool {
	if m != nil {
		return m.ActiveOnly
	}
	return false
}

type ListTasksResponse struct {
	ModelId              string   `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperparametersId    string   `protobuf:"bytes,2,opt,name=hyperparametersId,proto3" json:"hyperparametersId,omitempty"`
	CheckpointId         string   `protobuf:"bytes,3,opt,name=checkpointId,proto3" json:"checkpointId,omitempty"`
	StartTaskId          string   `protobuf:"bytes,4,opt,name=startTaskId,proto3" json:"startTaskId,omitempty"`
	MaxItems             int32    `protobuf:"varint,5,opt,name=maxItems,proto3" json:"maxItems,omitempty"`
	TaskIds              []string `protobuf:"bytes,6,rep,name=taskIds,proto3" json:"taskIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksResponse) Reset()         { *m = ListTasksResponse{} }
func (m *ListTasksResponse) String() string { return proto.CompactTextString(m) }
func (*ListTasksResponse) ProtoMessage()    {}
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{3}
}

func (m *ListTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksResponse.Unmarshal(m, b)
}
func (m *ListTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksResponse.Marshal(b, m, deterministic)
}
func (m *ListTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksResponse.Merge(m, src)
}
func (m *ListTasksResponse) XXX_Size() int {
	return xxx_messageInfo_ListTasksResponse.Size(m)
}
func (m *ListTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksResponse proto.InternalMessageInfo

func (m *ListTasksResponse) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *ListTasksResponse) GetHyperparametersId() string {
	if m != nil {
		return m.HyperparametersId
	}
	return ""
}

func (m *ListTasksResponse) GetCheckpointId() string {
	if m != nil {
		return m.CheckpointId
	}
	return ""
}

func (m *ListTasksResponse) GetStartTaskId() string {
	if m != nil {
		return m.StartTaskId
	}
	return ""
}

func (m *ListTasksResponse) GetMaxItems() int32 {
	if m != nil {
		return m.MaxItems
	}
	return 0
}

func (m *ListTasksResponse) GetTaskIds() []string {
	if m != nil {
		return m.TaskIds
	}
	return nil
}

type GetTaskRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskRequest) Reset()         { *m = GetTaskRequest{} }
func (m *GetTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GetTaskRequest) ProtoMessage()    {}
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{4}
}

func (m *GetTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskRequest.Unmarshal(m, b)
}
func (m *GetTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskRequest.Marshal(b, m, deterministic)
}
func (m *GetTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskRequest.Merge(m, src)
}
func (m *GetTaskRequest) XXX_Size() int {
	return xxx_messageInfo_GetTaskRequest.Size(m)
}
func (m *GetTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskRequest proto.InternalMessageInfo

func (m *GetTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

// This is returned by both /create_task, /task/<taskId> and /modify_task/<taskId>
type TaskDetails struct {
	ModelId              string   `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperparametersId    string   `protobuf:"bytes,2,opt,name=hyperparametersId,proto3" json:"hyperparametersId,omitempty"`
	CheckpointId         string   `protobuf:"bytes,3,opt,name=checkpointId,proto3" json:"checkpointId,omitempty"`
	Deadline             int64    `protobuf:"varint,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	TaskId               string   `protobuf:"bytes,5,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Active               bool     `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	TaskSpec             string   `protobuf:"bytes,7,opt,name=taskSpec,proto3" json:"taskSpec,omitempty"`
	ResourcePath         string   `protobuf:"bytes,8,opt,name=resourcePath,proto3" json:"resourcePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskDetails) Reset()         { *m = TaskDetails{} }
func (m *TaskDetails) String() string { return proto.CompactTextString(m) }
func (*TaskDetails) ProtoMessage()    {}
func (*TaskDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{5}
}

func (m *TaskDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDetails.Unmarshal(m, b)
}
func (m *TaskDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDetails.Marshal(b, m, deterministic)
}
func (m *TaskDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDetails.Merge(m, src)
}
func (m *TaskDetails) XXX_Size() int {
	return xxx_messageInfo_TaskDetails.Size(m)
}
func (m *TaskDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDetails.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDetails proto.InternalMessageInfo

func (m *TaskDetails) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *TaskDetails) GetHyperparametersId() string {
	if m != nil {
		return m.HyperparametersId
	}
	return ""
}

func (m *TaskDetails) GetCheckpointId() string {
	if m != nil {
		return m.CheckpointId
	}
	return ""
}

func (m *TaskDetails) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *TaskDetails) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *TaskDetails) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *TaskDetails) GetTaskSpec() string {
	if m != nil {
		return m.TaskSpec
	}
	return ""
}

func (m *TaskDetails) GetResourcePath() string {
	if m != nil {
		return m.ResourcePath
	}
	return ""
}

type StartTaskRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTaskRequest) Reset()         { *m = StartTaskRequest{} }
func (m *StartTaskRequest) String() string { return proto.CompactTextString(m) }
func (*StartTaskRequest) ProtoMessage()    {}
func (*StartTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{6}
}

func (m *StartTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTaskRequest.Unmarshal(m, b)
}
func (m *StartTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTaskRequest.Marshal(b, m, deterministic)
}
func (m *StartTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTaskRequest.Merge(m, src)
}
func (m *StartTaskRequest) XXX_Size() int {
	return xxx_messageInfo_StartTaskRequest.Size(m)
}
func (m *StartTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartTaskRequest proto.InternalMessageInfo

func (m *StartTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type StartTaskResponse struct {
	Status               StartTaskResponse_RequestStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.StartTaskResponse_RequestStatus" json:"status,omitempty"`
	JobId                string                          `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	UploadTo             string                          `protobuf:"bytes,3,opt,name=uploadTo,proto3" json:"uploadTo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *StartTaskResponse) Reset()         { *m = StartTaskResponse{} }
func (m *StartTaskResponse) String() string { return proto.CompactTextString(m) }
func (*StartTaskResponse) ProtoMessage()    {}
func (*StartTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{7}
}

func (m *StartTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTaskResponse.Unmarshal(m, b)
}
func (m *StartTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTaskResponse.Marshal(b, m, deterministic)
}
func (m *StartTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTaskResponse.Merge(m, src)
}
func (m *StartTaskResponse) XXX_Size() int {
	return xxx_messageInfo_StartTaskResponse.Size(m)
}
func (m *StartTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartTaskResponse proto.InternalMessageInfo

func (m *StartTaskResponse) GetStatus() StartTaskResponse_RequestStatus {
	if m != nil {
		return m.Status
	}
	return StartTaskResponse_UNKNOWN
}

func (m *StartTaskResponse) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *StartTaskResponse) GetUploadTo() string {
	if m != nil {
		return m.UploadTo
	}
	return ""
}

type FinishTaskRequest struct {
	TaskId               string                       `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Status               FinishTaskRequest_TaskStatus `protobuf:"varint,2,opt,name=status,proto3,enum=api.FinishTaskRequest_TaskStatus" json:"status,omitempty"`
	Error                string                       `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *FinishTaskRequest) Reset()         { *m = FinishTaskRequest{} }
func (m *FinishTaskRequest) String() string { return proto.CompactTextString(m) }
func (*FinishTaskRequest) ProtoMessage()    {}
func (*FinishTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{8}
}

func (m *FinishTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishTaskRequest.Unmarshal(m, b)
}
func (m *FinishTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishTaskRequest.Marshal(b, m, deterministic)
}
func (m *FinishTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishTaskRequest.Merge(m, src)
}
func (m *FinishTaskRequest) XXX_Size() int {
	return xxx_messageInfo_FinishTaskRequest.Size(m)
}
func (m *FinishTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinishTaskRequest proto.InternalMessageInfo

func (m *FinishTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *FinishTaskRequest) GetStatus() FinishTaskRequest_TaskStatus {
	if m != nil {
		return m.Status
	}
	return FinishTaskRequest_UNKNOWN
}

func (m *FinishTaskRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type FinishTaskResponse struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinishTaskResponse) Reset()         { *m = FinishTaskResponse{} }
func (m *FinishTaskResponse) String() string { return proto.CompactTextString(m) }
func (*FinishTaskResponse) ProtoMessage()    {}
func (*FinishTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{9}
}

func (m *FinishTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishTaskResponse.Unmarshal(m, b)
}
func (m *FinishTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishTaskResponse.Marshal(b, m, deterministic)
}
func (m *FinishTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishTaskResponse.Merge(m, src)
}
func (m *FinishTaskResponse) XXX_Size() int {
	return xxx_messageInfo_FinishTaskResponse.Size(m)
}
func (m *FinishTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FinishTaskResponse proto.InternalMessageInfo

func (m *FinishTaskResponse) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.StartTaskResponse_RequestStatus", StartTaskResponse_RequestStatus_name, StartTaskResponse_RequestStatus_value)
	proto.RegisterEnum("api.FinishTaskRequest_TaskStatus", FinishTaskRequest_TaskStatus_name, FinishTaskRequest_TaskStatus_value)
	proto.RegisterType((*CreateTaskRequest)(nil), "api.CreateTaskRequest")
	proto.RegisterType((*ModifyTaskRequest)(nil), "api.ModifyTaskRequest")
	proto.RegisterType((*ListTasksRequest)(nil), "api.ListTasksRequest")
	proto.RegisterType((*ListTasksResponse)(nil), "api.ListTasksResponse")
	proto.RegisterType((*GetTaskRequest)(nil), "api.GetTaskRequest")
	proto.RegisterType((*TaskDetails)(nil), "api.TaskDetails")
	proto.RegisterType((*StartTaskRequest)(nil), "api.StartTaskRequest")
	proto.RegisterType((*StartTaskResponse)(nil), "api.StartTaskResponse")
	proto.RegisterType((*FinishTaskRequest)(nil), "api.FinishTaskRequest")
	proto.RegisterType((*FinishTaskResponse)(nil), "api.FinishTaskResponse")
}

func init() { proto.RegisterFile("flea.proto", fileDescriptor_c48a4bf4882f2158) }

var fileDescriptor_c48a4bf4882f2158 = []byte{
	// 846 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xcd, 0x72, 0xe3, 0x44,
	0x10, 0x46, 0xfe, 0x77, 0x67, 0x37, 0x48, 0xb3, 0x8b, 0xad, 0x55, 0xed, 0x82, 0x19, 0x38, 0xb8,
	0xb6, 0x52, 0x76, 0x11, 0x2e, 0x40, 0x71, 0x20, 0x38, 0x0e, 0x38, 0x7f, 0x76, 0x29, 0x21, 0xb9,
	0x11, 0x26, 0xd6, 0x24, 0x16, 0x91, 0x35, 0x42, 0x33, 0x4e, 0x61, 0x28, 0x2e, 0x54, 0xf1, 0x04,
	0x3c, 0x0f, 0x3c, 0x00, 0x57, 0x0e, 0x5c, 0xa8, 0xe2, 0xc2, 0x83, 0x50, 0x33, 0x9a, 0xc8, 0xb2,
	0x15, 0x17, 0x39, 0x41, 0xed, 0xcd, 0xdd, 0xd3, 0xfd, 0x75, 0x7f, 0x9f, 0xba, 0x67, 0x0c, 0x70,
	0x15, 0x50, 0xd2, 0x89, 0x62, 0x26, 0x18, 0x2a, 0x92, 0xc8, 0x77, 0x9e, 0x5f, 0x33, 0x76, 0x1d,
	0xd0, 0x2e, 0x89, 0xfc, 0x2e, 0x09, 0x43, 0x26, 0x88, 0xf0, 0x59, 0xc8, 0x93, 0x10, 0xc7, 0x8c,
	0x69, 0xc4, 0xb8, 0x2f, 0x58, 0x3c, 0x4f, 0x3c, 0xf8, 0x2f, 0x03, 0xac, 0x5e, 0x4c, 0x89, 0xa0,
	0xa7, 0x84, 0xdf, 0xb8, 0xf4, 0x9b, 0x19, 0xe5, 0x02, 0xd9, 0x50, 0x9d, 0x32, 0x8f, 0x06, 0x03,
	0xcf, 0x36, 0x5a, 0x46, 0xbb, 0xee, 0xde, 0x99, 0x68, 0x0b, 0xac, 0xc9, 0x3c, 0xa2, 0x71, 0x44,
	0x62, 0x32, 0xa5, 0x82, 0xc6, 0x7c, 0xe0, 0xd9, 0x05, 0x15, 0x93, 0x3f, 0x40, 0x18, 0x1e, 0x8d,
	0x27, 0x74, 0x7c, 0x13, 0x31, 0x3f, 0x14, 0x03, 0xcf, 0x2e, 0xaa, 0xc0, 0x25, 0x1f, 0x6a, 0x40,
	0x45, 0x10, 0x7e, 0x33, 0xf0, 0xec, 0x92, 0x3a, 0xd5, 0x16, 0x72, 0xa0, 0xe6, 0x51, 0xe2, 0x05,
	0x7e, 0x48, 0xed, 0x72, 0xcb, 0x68, 0x17, 0xdd, 0xd4, 0x96, 0x39, 0x64, 0x2c, 0xfc, 0x5b, 0x6a,
	0x57, 0x5a, 0x46, 0xbb, 0xe6, 0x6a, 0x0b, 0x21, 0x28, 0xc9, 0x6c, 0xbb, 0xaa, 0x90, 0xd4, 0x6f,
	0x7c, 0x01, 0xd6, 0x11, 0xf3, 0xfc, 0xab, 0x79, 0x96, 0xe0, 0xa2, 0xa8, 0xb1, 0xb6, 0x68, 0x61,
	0x6d, 0xd1, 0x62, 0xb6, 0x28, 0xfe, 0xd3, 0x00, 0xf3, 0xd0, 0xe7, 0x42, 0xe2, 0xf3, 0xff, 0x43,
	0xc1, 0x16, 0x6c, 0x70, 0x41, 0x62, 0xd5, 0x40, 0x2a, 0x63, 0xd6, 0x25, 0x69, 0x4d, 0xc9, 0xb7,
	0x03, 0x41, 0xa7, 0x5c, 0x69, 0x59, 0x76, 0x53, 0x1b, 0xbd, 0x09, 0x90, 0x10, 0x19, 0x86, 0xc1,
	0x5c, 0xeb, 0x99, 0xf1, 0xe0, 0x3f, 0x0c, 0xb0, 0x32, 0xf4, 0x78, 0xc4, 0x42, 0x4e, 0x5f, 0x21,
	0x7e, 0x36, 0x54, 0x93, 0x8f, 0xcb, 0xed, 0x4a, 0xab, 0x28, 0x3b, 0xd5, 0x26, 0x6e, 0xc3, 0xe6,
	0x67, 0x54, 0x3c, 0x60, 0x2c, 0xf0, 0x4f, 0x05, 0xd8, 0x90, 0x71, 0xbb, 0x54, 0x10, 0x3f, 0xe0,
	0xff, 0x29, 0xfb, 0xec, 0x48, 0x96, 0xf2, 0x23, 0xa9, 0xfb, 0x2d, 0x2f, 0x8d, 0xf1, 0xba, 0xfd,
	0x70, 0xa0, 0x26, 0x23, 0x4e, 0x22, 0x3a, 0xd6, 0x3b, 0x92, 0xda, 0xb2, 0x97, 0x98, 0x72, 0x36,
	0x8b, 0xc7, 0x74, 0x44, 0xc4, 0xc4, 0xae, 0x25, 0xbd, 0x64, 0x7d, 0xf8, 0x25, 0x98, 0x27, 0x77,
	0xb2, 0xff, 0x9b, 0x66, 0xbf, 0x18, 0x60, 0x65, 0x82, 0xf5, 0xdc, 0x7c, 0x0c, 0x15, 0x2e, 0x88,
	0x98, 0x71, 0x15, 0xbd, 0xb9, 0xfd, 0x6e, 0x87, 0x44, 0x7e, 0x27, 0x17, 0xd7, 0xd1, 0xe8, 0x27,
	0x2a, 0xd6, 0xd5, 0x39, 0xe8, 0x29, 0x94, 0xbf, 0x66, 0x97, 0xa9, 0xa2, 0x89, 0x21, 0x59, 0xcd,
	0xa2, 0x80, 0x11, 0xef, 0x94, 0x69, 0x05, 0x53, 0x1b, 0x7f, 0x00, 0x8f, 0x97, 0xa0, 0xd0, 0x06,
	0x54, 0xbf, 0x38, 0x3e, 0x38, 0x1e, 0x9e, 0x1f, 0x9b, 0xaf, 0xa1, 0x47, 0x50, 0x73, 0xfb, 0xfb,
	0xfd, 0xde, 0x69, 0x7f, 0xd7, 0x34, 0xa4, 0xb5, 0x33, 0x1a, 0xb9, 0xc3, 0xb3, 0xfe, 0xae, 0x59,
	0xc0, 0xbf, 0x1a, 0x60, 0xed, 0xf9, 0xa1, 0xcf, 0x27, 0x0f, 0xb9, 0x38, 0x3e, 0x4c, 0x79, 0x15,
	0x14, 0xaf, 0xb7, 0x15, 0xaf, 0x5c, 0x7e, 0x47, 0xfe, 0xce, 0x93, 0xa2, 0x71, 0xcc, 0x62, 0xdd,
	0x7b, 0x62, 0xe0, 0x4f, 0x00, 0x16, 0xb1, 0xcb, 0x5d, 0x3f, 0x86, 0x7a, 0x6f, 0x78, 0x34, 0x3a,
	0xec, 0x27, 0x6d, 0xd7, 0xa1, 0xdc, 0x77, 0xdd, 0xa1, 0x6b, 0x16, 0x64, 0xd8, 0xce, 0xa7, 0x43,
	0x57, 0xfa, 0x8b, 0x78, 0x0b, 0x50, 0xb6, 0xbe, 0xfe, 0x00, 0x6b, 0x08, 0x6c, 0xff, 0x56, 0x86,
	0xd2, 0x5e, 0x40, 0x09, 0x3a, 0x83, 0xea, 0xe7, 0x94, 0x04, 0x62, 0xf2, 0x1d, 0x6a, 0x2a, 0x12,
	0x89, 0xd5, 0x93, 0x33, 0xa9, 0x59, 0x38, 0x76, 0xfe, 0x20, 0x81, 0xc7, 0xf6, 0x8f, 0xbf, 0xff,
	0xfd, 0x73, 0x01, 0x21, 0xb3, 0x7b, 0xfb, 0x5e, 0x57, 0x3e, 0x4e, 0xdd, 0x89, 0x06, 0xdb, 0x87,
	0x4a, 0x8f, 0x85, 0x57, 0xfe, 0x35, 0x42, 0x2a, 0x3b, 0x31, 0xee, 0x10, 0x9f, 0x2c, 0xf9, 0x34,
	0x58, 0x53, 0x81, 0x59, 0xe8, 0xf5, 0x14, 0x6c, 0x9c, 0x20, 0x9c, 0x03, 0x2c, 0x1e, 0x2d, 0xd4,
	0x48, 0x72, 0x57, 0x5f, 0x31, 0xc7, 0x54, 0xfe, 0xcc, 0xde, 0xe2, 0xb7, 0x14, 0xe0, 0x33, 0xfc,
	0x74, 0x01, 0xa8, 0xb2, 0x2e, 0xa4, 0x08, 0x1f, 0x19, 0x2f, 0xd1, 0x57, 0x00, 0x8b, 0xc7, 0x42,
	0x03, 0xe7, 0x5e, 0x8f, 0x7b, 0x80, 0xdb, 0x0a, 0x18, 0xe3, 0x17, 0x29, 0xf0, 0x54, 0x65, 0x29,
	0xe0, 0xee, 0xf7, 0x89, 0xc6, 0x3f, 0xc8, 0x0a, 0x2e, 0xd4, 0xd3, 0xdb, 0x14, 0xbd, 0xa1, 0x80,
	0x56, 0x1f, 0x0f, 0xa7, 0xb1, 0xea, 0xd6, 0x7a, 0x34, 0x54, 0x15, 0x13, 0x6d, 0xa6, 0x55, 0x84,
	0x82, 0x39, 0x80, 0xaa, 0xbe, 0xc8, 0x50, 0xa2, 0xe3, 0xf2, 0xb5, 0x76, 0x4f, 0xbf, 0xcf, 0x14,
	0xd2, 0x13, 0x64, 0x49, 0xa4, 0xa5, 0x1e, 0xd1, 0x97, 0x50, 0x4f, 0xd7, 0x51, 0x37, 0xb8, 0xba,
	0xf3, 0xba, 0xc1, 0xdc, 0xd6, 0x62, 0xac, 0x60, 0x9f, 0xe3, 0xa6, 0x84, 0x55, 0x17, 0x74, 0x5e,
	0x80, 0x4b, 0x80, 0xc5, 0x58, 0x6a, 0x89, 0x73, 0x7b, 0xe2, 0x34, 0x73, 0x7e, 0x5d, 0xe2, 0x1d,
	0x55, 0xe2, 0x05, 0xb6, 0x95, 0x06, 0xea, 0x3c, 0x57, 0xe3, 0xb2, 0xa2, 0xfe, 0xdc, 0xbc, 0xff,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x70, 0x7f, 0x3e, 0x1f, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FleaClient is the client API for Flea service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FleaClient interface {
	Healthz(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Config(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*TaskDetails, error)
	ModifyTask(ctx context.Context, in *ModifyTaskRequest, opts ...grpc.CallOption) (*TaskDetails, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskDetails, error)
	StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error)
	FinishTask(ctx context.Context, in *FinishTaskRequest, opts ...grpc.CallOption) (*FinishTaskResponse, error)
}

type fleaClient struct {
	cc *grpc.ClientConn
}

func NewFleaClient(cc *grpc.ClientConn) FleaClient {
	return &fleaClient{cc}
}

func (c *fleaClient) Healthz(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/api.Flea/Healthz", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) Config(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, "/api.Flea/Config", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*TaskDetails, error) {
	out := new(TaskDetails)
	err := c.cc.Invoke(ctx, "/api.Flea/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) ModifyTask(ctx context.Context, in *ModifyTaskRequest, opts ...grpc.CallOption) (*TaskDetails, error) {
	out := new(TaskDetails)
	err := c.cc.Invoke(ctx, "/api.Flea/ModifyTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, "/api.Flea/ListTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskDetails, error) {
	out := new(TaskDetails)
	err := c.cc.Invoke(ctx, "/api.Flea/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error) {
	out := new(StartTaskResponse)
	err := c.cc.Invoke(ctx, "/api.Flea/StartTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) FinishTask(ctx context.Context, in *FinishTaskRequest, opts ...grpc.CallOption) (*FinishTaskResponse, error) {
	out := new(FinishTaskResponse)
	err := c.cc.Invoke(ctx, "/api.Flea/FinishTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleaServer is the server API for Flea service.
type FleaServer interface {
	Healthz(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	Config(context.Context, *ConfigRequest) (*ConfigResponse, error)
	CreateTask(context.Context, *CreateTaskRequest) (*TaskDetails, error)
	ModifyTask(context.Context, *ModifyTaskRequest) (*TaskDetails, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*TaskDetails, error)
	StartTask(context.Context, *StartTaskRequest) (*StartTaskResponse, error)
	FinishTask(context.Context, *FinishTaskRequest) (*FinishTaskResponse, error)
}

func RegisterFleaServer(s *grpc.Server, srv FleaServer) {
	s.RegisterService(&_Flea_serviceDesc, srv)
}

func _Flea_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/Healthz",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).Healthz(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/Config",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).Config(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_ModifyTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).ModifyTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/ModifyTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).ModifyTask(ctx, req.(*ModifyTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/ListTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_StartTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).StartTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/StartTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).StartTask(ctx, req.(*StartTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_FinishTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).FinishTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/FinishTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).FinishTask(ctx, req.(*FinishTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Flea_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Flea",
	HandlerType: (*FleaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _Flea_Healthz_Handler,
		},
		{
			MethodName: "Config",
			Handler:    _Flea_Config_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _Flea_CreateTask_Handler,
		},
		{
			MethodName: "ModifyTask",
			Handler:    _Flea_ModifyTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _Flea_ListTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _Flea_GetTask_Handler,
		},
		{
			MethodName: "StartTask",
			Handler:    _Flea_StartTask_Handler,
		},
		{
			MethodName: "FinishTask",
			Handler:    _Flea_FinishTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flea.proto",
}
