// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flea.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartTaskResponse_RequestStatus int32

const (
	StartTaskResponse_UNKNOWN  StartTaskResponse_RequestStatus = 0
	StartTaskResponse_REJECTED StartTaskResponse_RequestStatus = 1
	StartTaskResponse_APPROVED StartTaskResponse_RequestStatus = 2
)

var StartTaskResponse_RequestStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "REJECTED",
	2: "APPROVED",
}

var StartTaskResponse_RequestStatus_value = map[string]int32{
	"UNKNOWN":  0,
	"REJECTED": 1,
	"APPROVED": 2,
}

func (x StartTaskResponse_RequestStatus) String() string {
	return proto.EnumName(StartTaskResponse_RequestStatus_name, int32(x))
}

func (StartTaskResponse_RequestStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{6, 0}
}

type AdminRequest_AdminRequestType int32

const (
	AdminRequest_UNKNOWN       AdminRequest_AdminRequestType = 0
	AdminRequest_RELOAD_TOKENS AdminRequest_AdminRequestType = 1
)

var AdminRequest_AdminRequestType_name = map[int32]string{
	0: "UNKNOWN",
	1: "RELOAD_TOKENS",
}

var AdminRequest_AdminRequestType_value = map[string]int32{
	"UNKNOWN":       0,
	"RELOAD_TOKENS": 1,
}

func (x AdminRequest_AdminRequestType) String() string {
	return proto.EnumName(AdminRequest_AdminRequestType_name, int32(x))
}

func (AdminRequest_AdminRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{7, 0}
}

type ModifyTaskRequest struct {
	TaskId               string               `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Deadline             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Active               bool                 `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ModifyTaskRequest) Reset()         { *m = ModifyTaskRequest{} }
func (m *ModifyTaskRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyTaskRequest) ProtoMessage()    {}
func (*ModifyTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{0}
}

func (m *ModifyTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyTaskRequest.Unmarshal(m, b)
}
func (m *ModifyTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyTaskRequest.Marshal(b, m, deterministic)
}
func (m *ModifyTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyTaskRequest.Merge(m, src)
}
func (m *ModifyTaskRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyTaskRequest.Size(m)
}
func (m *ModifyTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyTaskRequest proto.InternalMessageInfo

func (m *ModifyTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *ModifyTaskRequest) GetDeadline() *timestamp.Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

func (m *ModifyTaskRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type ListTasksRequest struct {
	ModelId           string `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperparametersId string `protobuf:"bytes,2,opt,name=hyperparametersId,proto3" json:"hyperparametersId,omitempty"`
	CheckpointId      string `protobuf:"bytes,3,opt,name=checkpointId,proto3" json:"checkpointId,omitempty"`
	// Tasks are returned lexicographically sorted by taskId
	// If specified only taskIds >= startTaskId will be returned.
	StartTaskId          string   `protobuf:"bytes,4,opt,name=startTaskId,proto3" json:"startTaskId,omitempty"`
	MaxItems             int32    `protobuf:"varint,5,opt,name=maxItems,proto3" json:"maxItems,omitempty"`
	IncludeInactive      bool     `protobuf:"varint,6,opt,name=includeInactive,proto3" json:"includeInactive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksRequest) Reset()         { *m = ListTasksRequest{} }
func (m *ListTasksRequest) String() string { return proto.CompactTextString(m) }
func (*ListTasksRequest) ProtoMessage()    {}
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{1}
}

func (m *ListTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksRequest.Unmarshal(m, b)
}
func (m *ListTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksRequest.Marshal(b, m, deterministic)
}
func (m *ListTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksRequest.Merge(m, src)
}
func (m *ListTasksRequest) XXX_Size() int {
	return xxx_messageInfo_ListTasksRequest.Size(m)
}
func (m *ListTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksRequest proto.InternalMessageInfo

func (m *ListTasksRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *ListTasksRequest) GetHyperparametersId() string {
	if m != nil {
		return m.HyperparametersId
	}
	return ""
}

func (m *ListTasksRequest) GetCheckpointId() string {
	if m != nil {
		return m.CheckpointId
	}
	return ""
}

func (m *ListTasksRequest) GetStartTaskId() string {
	if m != nil {
		return m.StartTaskId
	}
	return ""
}

func (m *ListTasksRequest) GetMaxItems() int32 {
	if m != nil {
		return m.MaxItems
	}
	return 0
}

func (m *ListTasksRequest) GetIncludeInactive() bool {
	if m != nil {
		return m.IncludeInactive
	}
	return false
}

type ListTasksResponse struct {
	StartTaskId          string   `protobuf:"bytes,1,opt,name=startTaskId,proto3" json:"startTaskId,omitempty"`
	MaxItems             int32    `protobuf:"varint,2,opt,name=maxItems,proto3" json:"maxItems,omitempty"`
	TaskIds              []string `protobuf:"bytes,3,rep,name=taskIds,proto3" json:"taskIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksResponse) Reset()         { *m = ListTasksResponse{} }
func (m *ListTasksResponse) String() string { return proto.CompactTextString(m) }
func (*ListTasksResponse) ProtoMessage()    {}
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{2}
}

func (m *ListTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksResponse.Unmarshal(m, b)
}
func (m *ListTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksResponse.Marshal(b, m, deterministic)
}
func (m *ListTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksResponse.Merge(m, src)
}
func (m *ListTasksResponse) XXX_Size() int {
	return xxx_messageInfo_ListTasksResponse.Size(m)
}
func (m *ListTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksResponse proto.InternalMessageInfo

func (m *ListTasksResponse) GetStartTaskId() string {
	if m != nil {
		return m.StartTaskId
	}
	return ""
}

func (m *ListTasksResponse) GetMaxItems() int32 {
	if m != nil {
		return m.MaxItems
	}
	return 0
}

func (m *ListTasksResponse) GetTaskIds() []string {
	if m != nil {
		return m.TaskIds
	}
	return nil
}

type GetTaskRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskRequest) Reset()         { *m = GetTaskRequest{} }
func (m *GetTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GetTaskRequest) ProtoMessage()    {}
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{3}
}

func (m *GetTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskRequest.Unmarshal(m, b)
}
func (m *GetTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskRequest.Marshal(b, m, deterministic)
}
func (m *GetTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskRequest.Merge(m, src)
}
func (m *GetTaskRequest) XXX_Size() int {
	return xxx_messageInfo_GetTaskRequest.Size(m)
}
func (m *GetTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskRequest proto.InternalMessageInfo

func (m *GetTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

// This is used by both /create_task, /task/<taskId> and /modify_task/<taskId>
type TaskDetails struct {
	ModelId              string               `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperparametersId    string               `protobuf:"bytes,2,opt,name=hyperparametersId,proto3" json:"hyperparametersId,omitempty"`
	CheckpointId         string               `protobuf:"bytes,3,opt,name=checkpointId,proto3" json:"checkpointId,omitempty"`
	Deadline             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	TaskId               string               `protobuf:"bytes,5,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Active               bool                 `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	Link                 string               `protobuf:"bytes,7,opt,name=link,proto3" json:"link,omitempty"`
	CheckpointLink       string               `protobuf:"bytes,8,opt,name=checkpointLink,proto3" json:"checkpointLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TaskDetails) Reset()         { *m = TaskDetails{} }
func (m *TaskDetails) String() string { return proto.CompactTextString(m) }
func (*TaskDetails) ProtoMessage()    {}
func (*TaskDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{4}
}

func (m *TaskDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDetails.Unmarshal(m, b)
}
func (m *TaskDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDetails.Marshal(b, m, deterministic)
}
func (m *TaskDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDetails.Merge(m, src)
}
func (m *TaskDetails) XXX_Size() int {
	return xxx_messageInfo_TaskDetails.Size(m)
}
func (m *TaskDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDetails.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDetails proto.InternalMessageInfo

func (m *TaskDetails) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *TaskDetails) GetHyperparametersId() string {
	if m != nil {
		return m.HyperparametersId
	}
	return ""
}

func (m *TaskDetails) GetCheckpointId() string {
	if m != nil {
		return m.CheckpointId
	}
	return ""
}

func (m *TaskDetails) GetDeadline() *timestamp.Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

func (m *TaskDetails) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *TaskDetails) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *TaskDetails) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *TaskDetails) GetCheckpointLink() string {
	if m != nil {
		return m.CheckpointLink
	}
	return ""
}

type StartTaskRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartTaskRequest) Reset()         { *m = StartTaskRequest{} }
func (m *StartTaskRequest) String() string { return proto.CompactTextString(m) }
func (*StartTaskRequest) ProtoMessage()    {}
func (*StartTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{5}
}

func (m *StartTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTaskRequest.Unmarshal(m, b)
}
func (m *StartTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTaskRequest.Marshal(b, m, deterministic)
}
func (m *StartTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTaskRequest.Merge(m, src)
}
func (m *StartTaskRequest) XXX_Size() int {
	return xxx_messageInfo_StartTaskRequest.Size(m)
}
func (m *StartTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartTaskRequest proto.InternalMessageInfo

func (m *StartTaskRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type StartTaskResponse struct {
	Status               StartTaskResponse_RequestStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.StartTaskResponse_RequestStatus" json:"status,omitempty"`
	JobId                string                          `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	UploadTo             string                          `protobuf:"bytes,3,opt,name=uploadTo,proto3" json:"uploadTo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *StartTaskResponse) Reset()         { *m = StartTaskResponse{} }
func (m *StartTaskResponse) String() string { return proto.CompactTextString(m) }
func (*StartTaskResponse) ProtoMessage()    {}
func (*StartTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{6}
}

func (m *StartTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartTaskResponse.Unmarshal(m, b)
}
func (m *StartTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartTaskResponse.Marshal(b, m, deterministic)
}
func (m *StartTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartTaskResponse.Merge(m, src)
}
func (m *StartTaskResponse) XXX_Size() int {
	return xxx_messageInfo_StartTaskResponse.Size(m)
}
func (m *StartTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartTaskResponse proto.InternalMessageInfo

func (m *StartTaskResponse) GetStatus() StartTaskResponse_RequestStatus {
	if m != nil {
		return m.Status
	}
	return StartTaskResponse_UNKNOWN
}

func (m *StartTaskResponse) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *StartTaskResponse) GetUploadTo() string {
	if m != nil {
		return m.UploadTo
	}
	return ""
}

type AdminRequest struct {
	Type                 AdminRequest_AdminRequestType `protobuf:"varint,1,opt,name=type,proto3,enum=api.AdminRequest_AdminRequestType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *AdminRequest) Reset()         { *m = AdminRequest{} }
func (m *AdminRequest) String() string { return proto.CompactTextString(m) }
func (*AdminRequest) ProtoMessage()    {}
func (*AdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{7}
}

func (m *AdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminRequest.Unmarshal(m, b)
}
func (m *AdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminRequest.Marshal(b, m, deterministic)
}
func (m *AdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminRequest.Merge(m, src)
}
func (m *AdminRequest) XXX_Size() int {
	return xxx_messageInfo_AdminRequest.Size(m)
}
func (m *AdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminRequest proto.InternalMessageInfo

func (m *AdminRequest) GetType() AdminRequest_AdminRequestType {
	if m != nil {
		return m.Type
	}
	return AdminRequest_UNKNOWN
}

type GenericResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericResponse) Reset()         { *m = GenericResponse{} }
func (m *GenericResponse) String() string { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()    {}
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{8}
}

func (m *GenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericResponse.Unmarshal(m, b)
}
func (m *GenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericResponse.Marshal(b, m, deterministic)
}
func (m *GenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericResponse.Merge(m, src)
}
func (m *GenericResponse) XXX_Size() int {
	return xxx_messageInfo_GenericResponse.Size(m)
}
func (m *GenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericResponse proto.InternalMessageInfo

func (m *GenericResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type JobErrorRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	JobId                string   `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobErrorRequest) Reset()         { *m = JobErrorRequest{} }
func (m *JobErrorRequest) String() string { return proto.CompactTextString(m) }
func (*JobErrorRequest) ProtoMessage()    {}
func (*JobErrorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c48a4bf4882f2158, []int{9}
}

func (m *JobErrorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobErrorRequest.Unmarshal(m, b)
}
func (m *JobErrorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobErrorRequest.Marshal(b, m, deterministic)
}
func (m *JobErrorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobErrorRequest.Merge(m, src)
}
func (m *JobErrorRequest) XXX_Size() int {
	return xxx_messageInfo_JobErrorRequest.Size(m)
}
func (m *JobErrorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobErrorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobErrorRequest proto.InternalMessageInfo

func (m *JobErrorRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *JobErrorRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *JobErrorRequest) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.StartTaskResponse_RequestStatus", StartTaskResponse_RequestStatus_name, StartTaskResponse_RequestStatus_value)
	proto.RegisterEnum("api.AdminRequest_AdminRequestType", AdminRequest_AdminRequestType_name, AdminRequest_AdminRequestType_value)
	proto.RegisterType((*ModifyTaskRequest)(nil), "api.ModifyTaskRequest")
	proto.RegisterType((*ListTasksRequest)(nil), "api.ListTasksRequest")
	proto.RegisterType((*ListTasksResponse)(nil), "api.ListTasksResponse")
	proto.RegisterType((*GetTaskRequest)(nil), "api.GetTaskRequest")
	proto.RegisterType((*TaskDetails)(nil), "api.TaskDetails")
	proto.RegisterType((*StartTaskRequest)(nil), "api.StartTaskRequest")
	proto.RegisterType((*StartTaskResponse)(nil), "api.StartTaskResponse")
	proto.RegisterType((*AdminRequest)(nil), "api.AdminRequest")
	proto.RegisterType((*GenericResponse)(nil), "api.GenericResponse")
	proto.RegisterType((*JobErrorRequest)(nil), "api.JobErrorRequest")
}

func init() { proto.RegisterFile("flea.proto", fileDescriptor_c48a4bf4882f2158) }

var fileDescriptor_c48a4bf4882f2158 = []byte{
	// 908 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x66, 0x1d, 0xff, 0x9e, 0xa4, 0xc9, 0x7a, 0x1a, 0x92, 0xad, 0x55, 0xa8, 0x35, 0x54, 0xc8,
	0x0a, 0xc8, 0x16, 0x41, 0xaa, 0x50, 0xc5, 0x4d, 0x94, 0x98, 0xe2, 0x24, 0x4d, 0xda, 0x8d, 0x29,
	0x97, 0xe9, 0xd8, 0x3b, 0x8e, 0xa7, 0x5e, 0xef, 0x2c, 0x3b, 0xe3, 0x0a, 0x37, 0xe2, 0x86, 0x57,
	0xe0, 0xba, 0x8f, 0xc2, 0x53, 0xf0, 0x0a, 0x88, 0xe7, 0x40, 0x7b, 0x76, 0xbc, 0xf6, 0xae, 0x5b,
	0x0a, 0x37, 0xdc, 0xed, 0x39, 0x73, 0xe6, 0xfb, 0xce, 0x7c, 0xf3, 0xcd, 0x59, 0x80, 0x91, 0xcf,
	0x59, 0x3b, 0x8c, 0xa4, 0x96, 0x64, 0x83, 0x85, 0xa2, 0xf1, 0xe0, 0x46, 0xca, 0x1b, 0x9f, 0x77,
	0x30, 0x35, 0x98, 0x8d, 0x3a, 0x5a, 0x4c, 0xb9, 0xd2, 0x6c, 0x1a, 0x26, 0x55, 0x8d, 0xfb, 0xa6,
	0x80, 0x85, 0xa2, 0xc3, 0x82, 0x40, 0x6a, 0xa6, 0x85, 0x0c, 0x94, 0x59, 0xb5, 0x23, 0x1e, 0x4a,
	0x25, 0xb4, 0x8c, 0xe6, 0x49, 0x86, 0xde, 0x42, 0xfd, 0xa9, 0xf4, 0xc4, 0x68, 0xde, 0x67, 0x6a,
	0xe2, 0xf2, 0x9f, 0x66, 0x5c, 0x69, 0xb2, 0x07, 0x65, 0xcd, 0xd4, 0xa4, 0xe7, 0x39, 0x56, 0xd3,
	0x6a, 0xd5, 0x5c, 0x13, 0x91, 0x47, 0x50, 0xf5, 0x38, 0xf3, 0x7c, 0x11, 0x70, 0xa7, 0xd0, 0xb4,
	0x5a, 0x9b, 0x87, 0x8d, 0x76, 0xc2, 0xd7, 0x5e, 0x34, 0xd4, 0xee, 0x2f, 0x1a, 0x72, 0xd3, 0xda,
	0x18, 0x8f, 0x0d, 0xb5, 0x78, 0xcd, 0x9d, 0x8d, 0xa6, 0xd5, 0xaa, 0xba, 0x26, 0xa2, 0x7f, 0x59,
	0x60, 0x9f, 0x0b, 0xa5, 0x63, 0x6e, 0xb5, 0x20, 0x77, 0xa0, 0x32, 0x95, 0x1e, 0xf7, 0x53, 0xf6,
	0x45, 0x48, 0xbe, 0x84, 0xfa, 0x78, 0x1e, 0xf2, 0x28, 0x64, 0x11, 0x9b, 0x72, 0xcd, 0x23, 0xd5,
	0xf3, 0xb0, 0x8f, 0x9a, 0xbb, 0xbe, 0x40, 0x28, 0x6c, 0x0d, 0xc7, 0x7c, 0x38, 0x09, 0xa5, 0x08,
	0x74, 0xcf, 0x43, 0xea, 0x9a, 0x9b, 0xc9, 0x91, 0x26, 0x6c, 0x2a, 0xcd, 0x22, 0x6c, 0xa0, 0xe7,
	0x39, 0x45, 0x2c, 0x59, 0x4d, 0x91, 0x06, 0x54, 0xa7, 0xec, 0xe7, 0x9e, 0xe6, 0x53, 0xe5, 0x94,
	0x9a, 0x56, 0xab, 0xe4, 0xa6, 0x31, 0x69, 0xc1, 0x8e, 0x08, 0x86, 0xfe, 0xcc, 0xe3, 0xbd, 0xc0,
	0x9c, 0xaf, 0x8c, 0xe7, 0xcb, 0xa7, 0xe9, 0x04, 0xea, 0x2b, 0xe7, 0x54, 0xa1, 0x0c, 0x14, 0xcf,
	0x93, 0x5b, 0xff, 0x4c, 0x5e, 0xc8, 0x91, 0x3b, 0x50, 0x49, 0x6e, 0x45, 0x39, 0x1b, 0xcd, 0x8d,
	0x58, 0x26, 0x13, 0xd2, 0x16, 0x6c, 0x3f, 0xe1, 0xfa, 0x5f, 0xdc, 0x27, 0x7d, 0x5b, 0x80, 0xcd,
	0xb8, 0xee, 0x84, 0x6b, 0x26, 0x7c, 0xf5, 0xbf, 0x4a, 0xbf, 0xea, 0xa5, 0xe2, 0x7f, 0xf3, 0x92,
	0x39, 0x4b, 0x29, 0xe3, 0xcd, 0xa5, 0xc7, 0xca, 0xab, 0x1e, 0x23, 0x04, 0x8a, 0xbe, 0x08, 0x26,
	0x4e, 0x05, 0xab, 0xf1, 0x9b, 0x7c, 0x0e, 0xdb, 0xcb, 0x5e, 0xce, 0xe3, 0xd5, 0x2a, 0xae, 0xe6,
	0xb2, 0xf4, 0x00, 0xec, 0xab, 0xc5, 0x75, 0x7c, 0x48, 0xcb, 0xdf, 0x2d, 0xa8, 0xaf, 0x14, 0x9b,
	0x3b, 0xfe, 0x16, 0xca, 0x4a, 0x33, 0x3d, 0x53, 0x58, 0xbd, 0x7d, 0xf8, 0xb0, 0xcd, 0x42, 0xd1,
	0x5e, 0xab, 0x6b, 0x1b, 0xf4, 0x2b, 0xac, 0x75, 0xcd, 0x1e, 0xb2, 0x0b, 0xa5, 0x57, 0x72, 0x90,
	0x2a, 0x9d, 0x04, 0xb1, 0x2b, 0x66, 0xa1, 0x2f, 0x99, 0xd7, 0x97, 0x46, 0xd9, 0x34, 0xa6, 0xdf,
	0xc0, 0x9d, 0x0c, 0x14, 0xd9, 0x84, 0xca, 0x0f, 0x17, 0x67, 0x17, 0x97, 0x3f, 0x5e, 0xd8, 0x1f,
	0x91, 0x2d, 0xa8, 0xba, 0xdd, 0xd3, 0xee, 0x71, 0xbf, 0x7b, 0x62, 0x5b, 0x71, 0x74, 0xf4, 0xec,
	0x99, 0x7b, 0xf9, 0xa2, 0x7b, 0x62, 0x17, 0xe8, 0x1b, 0xd8, 0x3a, 0xf2, 0xa6, 0x22, 0x58, 0x9c,
	0xf3, 0x11, 0x14, 0xf5, 0x3c, 0xe4, 0xa6, 0x6f, 0x8a, 0x7d, 0xaf, 0x16, 0x64, 0x82, 0xfe, 0x3c,
	0xe4, 0x2e, 0xd6, 0xd3, 0x43, 0xb0, 0xf3, 0x2b, 0xd9, 0x26, 0xea, 0x70, 0xc7, 0xed, 0x9e, 0x5f,
	0x1e, 0x9d, 0x5c, 0xf7, 0x2f, 0xcf, 0xba, 0x17, 0x57, 0xb6, 0x45, 0xbf, 0x80, 0x9d, 0x27, 0x3c,
	0xe0, 0x91, 0x18, 0xa6, 0xc2, 0xc5, 0x56, 0xe4, 0x4a, 0xb1, 0x1b, 0x9e, 0x5a, 0x31, 0x09, 0xe9,
	0x10, 0x76, 0x4e, 0xe5, 0xa0, 0x1b, 0x45, 0x32, 0xfa, 0xd0, 0xbc, 0x7a, 0xb7, 0x7e, 0x14, 0xb6,
	0x78, 0xbc, 0xfb, 0xa9, 0xc1, 0x37, 0xee, 0x5c, 0xcd, 0x1d, 0xbe, 0x2d, 0x43, 0xf1, 0x3b, 0x9f,
	0x33, 0xf2, 0x02, 0x2a, 0xdf, 0x73, 0xe6, 0xeb, 0xf1, 0x1b, 0xb2, 0x8f, 0x1a, 0x24, 0xd1, 0x71,
	0x6c, 0x14, 0x43, 0xdf, 0x70, 0xd6, 0x17, 0x92, 0x53, 0x50, 0xe7, 0xd7, 0x3f, 0xfe, 0xfc, 0xad,
	0x40, 0x88, 0xdd, 0x79, 0xfd, 0x55, 0x27, 0x9e, 0xe5, 0x9d, 0xb1, 0x01, 0x3b, 0x85, 0xf2, 0xb1,
	0x0c, 0x46, 0xe2, 0x86, 0x10, 0xdc, 0x9d, 0x04, 0x0b, 0xc4, 0xbb, 0x99, 0x9c, 0x01, 0xdb, 0x47,
	0xb0, 0x3a, 0xd9, 0x49, 0xc1, 0x86, 0x09, 0xc2, 0x73, 0x80, 0xe3, 0x88, 0x33, 0xcd, 0x63, 0x4b,
	0x11, 0x1b, 0xf7, 0xae, 0x3c, 0xeb, 0xc6, 0x5a, 0x86, 0x3e, 0x40, 0xa8, 0x7b, 0x74, 0x77, 0x09,
	0x85, 0x00, 0xd7, 0xb1, 0x70, 0x8f, 0xad, 0x03, 0xf2, 0x12, 0x60, 0xf9, 0x5b, 0x20, 0x7b, 0x08,
	0xb0, 0xf6, 0x9f, 0x78, 0x07, 0x70, 0x0b, 0x81, 0x29, 0xfd, 0x24, 0x05, 0x9e, 0xe2, 0x2e, 0x04,
	0xee, 0xdc, 0x26, 0xf7, 0xf2, 0x4b, 0xcc, 0xe0, 0x42, 0x2d, 0x1d, 0x89, 0xe4, 0x63, 0x04, 0xca,
	0xff, 0x0a, 0x1a, 0x7b, 0xf9, 0xb4, 0x51, 0x62, 0x0f, 0x59, 0x6c, 0xb2, 0x9d, 0xb2, 0x68, 0x84,
	0x79, 0x0e, 0x15, 0x33, 0xf9, 0x48, 0xa2, 0x60, 0x76, 0x0e, 0xbe, 0x5f, 0x08, 0xb2, 0x9f, 0x45,
	0x4a, 0x3b, 0x25, 0x2f, 0xa1, 0x96, 0xbe, 0x56, 0xd3, 0x66, 0x7e, 0x24, 0x98, 0x36, 0xd7, 0x1e,
	0x35, 0x7d, 0x88, 0xe0, 0x9f, 0x92, 0xfb, 0x29, 0x38, 0x0e, 0xf7, 0xac, 0x16, 0x64, 0x04, 0xd5,
	0x85, 0x9f, 0xc9, 0x2e, 0x22, 0xe5, 0xec, 0xdd, 0xd8, 0x35, 0x67, 0xc9, 0xbc, 0x10, 0xda, 0x46,
	0xf4, 0x16, 0xfd, 0x2c, 0x45, 0x7f, 0x25, 0x07, 0xd7, 0xe8, 0xe2, 0x14, 0xbc, 0x73, 0x8b, 0x96,
	0x47, 0xc1, 0xcf, 0xa0, 0x84, 0x0f, 0x93, 0xd4, 0xd7, 0xde, 0xf2, 0x7b, 0x18, 0xee, 0x21, 0xc3,
	0x5d, 0xba, 0x94, 0x99, 0xc5, 0x9b, 0x1e, 0x5b, 0x07, 0x83, 0x32, 0xce, 0xe8, 0xaf, 0xff, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0xbc, 0x2c, 0x16, 0x5b, 0xa1, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FleaClient is the client API for Flea service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FleaClient interface {
	Healthz(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Config(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	CreateTask(ctx context.Context, in *TaskDetails, opts ...grpc.CallOption) (*TaskDetails, error)
	ModifyTask(ctx context.Context, in *ModifyTaskRequest, opts ...grpc.CallOption) (*TaskDetails, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskDetails, error)
	StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error)
	JobError(ctx context.Context, in *JobErrorRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	Admin(ctx context.Context, in *AdminRequest, opts ...grpc.CallOption) (*GenericResponse, error)
}

type fleaClient struct {
	cc *grpc.ClientConn
}

func NewFleaClient(cc *grpc.ClientConn) FleaClient {
	return &fleaClient{cc}
}

func (c *fleaClient) Healthz(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/api.Flea/Healthz", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) Config(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, "/api.Flea/Config", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) CreateTask(ctx context.Context, in *TaskDetails, opts ...grpc.CallOption) (*TaskDetails, error) {
	out := new(TaskDetails)
	err := c.cc.Invoke(ctx, "/api.Flea/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) ModifyTask(ctx context.Context, in *ModifyTaskRequest, opts ...grpc.CallOption) (*TaskDetails, error) {
	out := new(TaskDetails)
	err := c.cc.Invoke(ctx, "/api.Flea/ModifyTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, "/api.Flea/ListTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*TaskDetails, error) {
	out := new(TaskDetails)
	err := c.cc.Invoke(ctx, "/api.Flea/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error) {
	out := new(StartTaskResponse)
	err := c.cc.Invoke(ctx, "/api.Flea/StartTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) JobError(ctx context.Context, in *JobErrorRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/api.Flea/JobError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleaClient) Admin(ctx context.Context, in *AdminRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/api.Flea/Admin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleaServer is the server API for Flea service.
type FleaServer interface {
	Healthz(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	Config(context.Context, *ConfigRequest) (*ConfigResponse, error)
	CreateTask(context.Context, *TaskDetails) (*TaskDetails, error)
	ModifyTask(context.Context, *ModifyTaskRequest) (*TaskDetails, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*TaskDetails, error)
	StartTask(context.Context, *StartTaskRequest) (*StartTaskResponse, error)
	JobError(context.Context, *JobErrorRequest) (*GenericResponse, error)
	Admin(context.Context, *AdminRequest) (*GenericResponse, error)
}

func RegisterFleaServer(s *grpc.Server, srv FleaServer) {
	s.RegisterService(&_Flea_serviceDesc, srv)
}

func _Flea_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/Healthz",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).Healthz(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/Config",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).Config(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).CreateTask(ctx, req.(*TaskDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_ModifyTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).ModifyTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/ModifyTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).ModifyTask(ctx, req.(*ModifyTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/ListTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_StartTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).StartTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/StartTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).StartTask(ctx, req.(*StartTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_JobError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).JobError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/JobError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).JobError(ctx, req.(*JobErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flea_Admin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleaServer).Admin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Flea/Admin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleaServer).Admin(ctx, req.(*AdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Flea_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Flea",
	HandlerType: (*FleaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _Flea_Healthz_Handler,
		},
		{
			MethodName: "Config",
			Handler:    _Flea_Config_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _Flea_CreateTask_Handler,
		},
		{
			MethodName: "ModifyTask",
			Handler:    _Flea_ModifyTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _Flea_ListTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _Flea_GetTask_Handler,
		},
		{
			MethodName: "StartTask",
			Handler:    _Flea_StartTask_Handler,
		},
		{
			MethodName: "JobError",
			Handler:    _Flea_JobError_Handler,
		},
		{
			MethodName: "Admin",
			Handler:    _Flea_Admin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flea.proto",
}
