// Code generated by protoc-gen-go. DO NOT EDIT.
// source: repository.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}

var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}

func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{1, 0}
}

//*
// Health checks inspired by the conventions here:
// https://github.com/grpc/grpc/blob/master/doc/health-checking.md
// (although they do not follow that protocol exactly)
//
// Exposed using the Healthz method on the Repository service.
type HealthCheckRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{0}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

func (m *HealthCheckRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type HealthCheckResponse struct {
	Status               HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{1}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

type Model struct {
	ModelId                  string   `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	Description              string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CanonicalHyperParameters string   `protobuf:"bytes,3,opt,name=canonicalHyperParameters,proto3" json:"canonicalHyperParameters,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{2}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *Model) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Model) GetCanonicalHyperParameters() string {
	if m != nil {
		return m.CanonicalHyperParameters
	}
	return ""
}

type ListModelsRequest struct {
	Marker               string   `protobuf:"bytes,1,opt,name=marker,proto3" json:"marker,omitempty"`
	MaxItems             int32    `protobuf:"varint,2,opt,name=maxItems,proto3" json:"maxItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListModelsRequest) Reset()         { *m = ListModelsRequest{} }
func (m *ListModelsRequest) String() string { return proto.CompactTextString(m) }
func (*ListModelsRequest) ProtoMessage()    {}
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{3}
}

func (m *ListModelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModelsRequest.Unmarshal(m, b)
}
func (m *ListModelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModelsRequest.Marshal(b, m, deterministic)
}
func (m *ListModelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModelsRequest.Merge(m, src)
}
func (m *ListModelsRequest) XXX_Size() int {
	return xxx_messageInfo_ListModelsRequest.Size(m)
}
func (m *ListModelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListModelsRequest proto.InternalMessageInfo

func (m *ListModelsRequest) GetMarker() string {
	if m != nil {
		return m.Marker
	}
	return ""
}

func (m *ListModelsRequest) GetMaxItems() int32 {
	if m != nil {
		return m.MaxItems
	}
	return 0
}

type ListModelsResponse struct {
	ModelIds             []string `protobuf:"bytes,1,rep,name=modelIds,proto3" json:"modelIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListModelsResponse) Reset()         { *m = ListModelsResponse{} }
func (m *ListModelsResponse) String() string { return proto.CompactTextString(m) }
func (*ListModelsResponse) ProtoMessage()    {}
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{4}
}

func (m *ListModelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModelsResponse.Unmarshal(m, b)
}
func (m *ListModelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModelsResponse.Marshal(b, m, deterministic)
}
func (m *ListModelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModelsResponse.Merge(m, src)
}
func (m *ListModelsResponse) XXX_Size() int {
	return xxx_messageInfo_ListModelsResponse.Size(m)
}
func (m *ListModelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListModelsResponse proto.InternalMessageInfo

func (m *ListModelsResponse) GetModelIds() []string {
	if m != nil {
		return m.ModelIds
	}
	return nil
}

type CreateModelRequest struct {
	Model                *Model   `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateModelRequest) Reset()         { *m = CreateModelRequest{} }
func (m *CreateModelRequest) String() string { return proto.CompactTextString(m) }
func (*CreateModelRequest) ProtoMessage()    {}
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{5}
}

func (m *CreateModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateModelRequest.Unmarshal(m, b)
}
func (m *CreateModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateModelRequest.Marshal(b, m, deterministic)
}
func (m *CreateModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateModelRequest.Merge(m, src)
}
func (m *CreateModelRequest) XXX_Size() int {
	return xxx_messageInfo_CreateModelRequest.Size(m)
}
func (m *CreateModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateModelRequest proto.InternalMessageInfo

func (m *CreateModelRequest) GetModel() *Model {
	if m != nil {
		return m.Model
	}
	return nil
}

type CreateModelResponse struct {
	ResourcePath         string   `protobuf:"bytes,1,opt,name=resourcePath,proto3" json:"resourcePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateModelResponse) Reset()         { *m = CreateModelResponse{} }
func (m *CreateModelResponse) String() string { return proto.CompactTextString(m) }
func (*CreateModelResponse) ProtoMessage()    {}
func (*CreateModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{6}
}

func (m *CreateModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateModelResponse.Unmarshal(m, b)
}
func (m *CreateModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateModelResponse.Marshal(b, m, deterministic)
}
func (m *CreateModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateModelResponse.Merge(m, src)
}
func (m *CreateModelResponse) XXX_Size() int {
	return xxx_messageInfo_CreateModelResponse.Size(m)
}
func (m *CreateModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateModelResponse proto.InternalMessageInfo

func (m *CreateModelResponse) GetResourcePath() string {
	if m != nil {
		return m.ResourcePath
	}
	return ""
}

type GetModelRequest struct {
	ModelId              string   `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetModelRequest) Reset()         { *m = GetModelRequest{} }
func (m *GetModelRequest) String() string { return proto.CompactTextString(m) }
func (*GetModelRequest) ProtoMessage()    {}
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{7}
}

func (m *GetModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetModelRequest.Unmarshal(m, b)
}
func (m *GetModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetModelRequest.Marshal(b, m, deterministic)
}
func (m *GetModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetModelRequest.Merge(m, src)
}
func (m *GetModelRequest) XXX_Size() int {
	return xxx_messageInfo_GetModelRequest.Size(m)
}
func (m *GetModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetModelRequest proto.InternalMessageInfo

func (m *GetModelRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

type GetModelResponse struct {
	Model                *Model   `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetModelResponse) Reset()         { *m = GetModelResponse{} }
func (m *GetModelResponse) String() string { return proto.CompactTextString(m) }
func (*GetModelResponse) ProtoMessage()    {}
func (*GetModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{8}
}

func (m *GetModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetModelResponse.Unmarshal(m, b)
}
func (m *GetModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetModelResponse.Marshal(b, m, deterministic)
}
func (m *GetModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetModelResponse.Merge(m, src)
}
func (m *GetModelResponse) XXX_Size() int {
	return xxx_messageInfo_GetModelResponse.Size(m)
}
func (m *GetModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetModelResponse proto.InternalMessageInfo

func (m *GetModelResponse) GetModel() *Model {
	if m != nil {
		return m.Model
	}
	return nil
}

type UpdateModelRequest struct {
	ModelId              string   `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	Model                *Model   `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateModelRequest) Reset()         { *m = UpdateModelRequest{} }
func (m *UpdateModelRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateModelRequest) ProtoMessage()    {}
func (*UpdateModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{9}
}

func (m *UpdateModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateModelRequest.Unmarshal(m, b)
}
func (m *UpdateModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateModelRequest.Marshal(b, m, deterministic)
}
func (m *UpdateModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateModelRequest.Merge(m, src)
}
func (m *UpdateModelRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateModelRequest.Size(m)
}
func (m *UpdateModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateModelRequest proto.InternalMessageInfo

func (m *UpdateModelRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *UpdateModelRequest) GetModel() *Model {
	if m != nil {
		return m.Model
	}
	return nil
}

type UpdateModelResponse struct {
	Model                *Model   `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateModelResponse) Reset()         { *m = UpdateModelResponse{} }
func (m *UpdateModelResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateModelResponse) ProtoMessage()    {}
func (*UpdateModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{10}
}

func (m *UpdateModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateModelResponse.Unmarshal(m, b)
}
func (m *UpdateModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateModelResponse.Marshal(b, m, deterministic)
}
func (m *UpdateModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateModelResponse.Merge(m, src)
}
func (m *UpdateModelResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateModelResponse.Size(m)
}
func (m *UpdateModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateModelResponse proto.InternalMessageInfo

func (m *UpdateModelResponse) GetModel() *Model {
	if m != nil {
		return m.Model
	}
	return nil
}

type ListHyperParametersRequest struct {
	ModelId              string   `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	Marker               string   `protobuf:"bytes,2,opt,name=marker,proto3" json:"marker,omitempty"`
	MaxItems             int32    `protobuf:"varint,3,opt,name=maxItems,proto3" json:"maxItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHyperParametersRequest) Reset()         { *m = ListHyperParametersRequest{} }
func (m *ListHyperParametersRequest) String() string { return proto.CompactTextString(m) }
func (*ListHyperParametersRequest) ProtoMessage()    {}
func (*ListHyperParametersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{11}
}

func (m *ListHyperParametersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHyperParametersRequest.Unmarshal(m, b)
}
func (m *ListHyperParametersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHyperParametersRequest.Marshal(b, m, deterministic)
}
func (m *ListHyperParametersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHyperParametersRequest.Merge(m, src)
}
func (m *ListHyperParametersRequest) XXX_Size() int {
	return xxx_messageInfo_ListHyperParametersRequest.Size(m)
}
func (m *ListHyperParametersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHyperParametersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHyperParametersRequest proto.InternalMessageInfo

func (m *ListHyperParametersRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *ListHyperParametersRequest) GetMarker() string {
	if m != nil {
		return m.Marker
	}
	return ""
}

func (m *ListHyperParametersRequest) GetMaxItems() int32 {
	if m != nil {
		return m.MaxItems
	}
	return 0
}

type ListHyperParametersResponse struct {
	HyperParametersIds   []string `protobuf:"bytes,1,rep,name=hyperParametersIds,proto3" json:"hyperParametersIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHyperParametersResponse) Reset()         { *m = ListHyperParametersResponse{} }
func (m *ListHyperParametersResponse) String() string { return proto.CompactTextString(m) }
func (*ListHyperParametersResponse) ProtoMessage()    {}
func (*ListHyperParametersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{12}
}

func (m *ListHyperParametersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHyperParametersResponse.Unmarshal(m, b)
}
func (m *ListHyperParametersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHyperParametersResponse.Marshal(b, m, deterministic)
}
func (m *ListHyperParametersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHyperParametersResponse.Merge(m, src)
}
func (m *ListHyperParametersResponse) XXX_Size() int {
	return xxx_messageInfo_ListHyperParametersResponse.Size(m)
}
func (m *ListHyperParametersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHyperParametersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListHyperParametersResponse proto.InternalMessageInfo

func (m *ListHyperParametersResponse) GetHyperParametersIds() []string {
	if m != nil {
		return m.HyperParametersIds
	}
	return nil
}

type CreateHyperParametersRequest struct {
	ModelId              string            `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperParametersId    string            `protobuf:"bytes,2,opt,name=hyperParametersId,proto3" json:"hyperParametersId,omitempty"`
	CanonicalCheckpoint  string            `protobuf:"bytes,3,opt,name=canonicalCheckpoint,proto3" json:"canonicalCheckpoint,omitempty"`
	HyperParameters      map[string]string `protobuf:"bytes,4,rep,name=hyperParameters,proto3" json:"hyperParameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateHyperParametersRequest) Reset()         { *m = CreateHyperParametersRequest{} }
func (m *CreateHyperParametersRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHyperParametersRequest) ProtoMessage()    {}
func (*CreateHyperParametersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{13}
}

func (m *CreateHyperParametersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHyperParametersRequest.Unmarshal(m, b)
}
func (m *CreateHyperParametersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHyperParametersRequest.Marshal(b, m, deterministic)
}
func (m *CreateHyperParametersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHyperParametersRequest.Merge(m, src)
}
func (m *CreateHyperParametersRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHyperParametersRequest.Size(m)
}
func (m *CreateHyperParametersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHyperParametersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHyperParametersRequest proto.InternalMessageInfo

func (m *CreateHyperParametersRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *CreateHyperParametersRequest) GetHyperParametersId() string {
	if m != nil {
		return m.HyperParametersId
	}
	return ""
}

func (m *CreateHyperParametersRequest) GetCanonicalCheckpoint() string {
	if m != nil {
		return m.CanonicalCheckpoint
	}
	return ""
}

func (m *CreateHyperParametersRequest) GetHyperParameters() map[string]string {
	if m != nil {
		return m.HyperParameters
	}
	return nil
}

type CreateHyperParametersResponse struct {
	ResourcePath         string   `protobuf:"bytes,1,opt,name=resourcePath,proto3" json:"resourcePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHyperParametersResponse) Reset()         { *m = CreateHyperParametersResponse{} }
func (m *CreateHyperParametersResponse) String() string { return proto.CompactTextString(m) }
func (*CreateHyperParametersResponse) ProtoMessage()    {}
func (*CreateHyperParametersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{14}
}

func (m *CreateHyperParametersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHyperParametersResponse.Unmarshal(m, b)
}
func (m *CreateHyperParametersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHyperParametersResponse.Marshal(b, m, deterministic)
}
func (m *CreateHyperParametersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHyperParametersResponse.Merge(m, src)
}
func (m *CreateHyperParametersResponse) XXX_Size() int {
	return xxx_messageInfo_CreateHyperParametersResponse.Size(m)
}
func (m *CreateHyperParametersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHyperParametersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHyperParametersResponse proto.InternalMessageInfo

func (m *CreateHyperParametersResponse) GetResourcePath() string {
	if m != nil {
		return m.ResourcePath
	}
	return ""
}

type GetHyperParametersRequest struct {
	ModelId              string   `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperParametersId    string   `protobuf:"bytes,2,opt,name=hyperParametersId,proto3" json:"hyperParametersId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHyperParametersRequest) Reset()         { *m = GetHyperParametersRequest{} }
func (m *GetHyperParametersRequest) String() string { return proto.CompactTextString(m) }
func (*GetHyperParametersRequest) ProtoMessage()    {}
func (*GetHyperParametersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{15}
}

func (m *GetHyperParametersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHyperParametersRequest.Unmarshal(m, b)
}
func (m *GetHyperParametersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHyperParametersRequest.Marshal(b, m, deterministic)
}
func (m *GetHyperParametersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHyperParametersRequest.Merge(m, src)
}
func (m *GetHyperParametersRequest) XXX_Size() int {
	return xxx_messageInfo_GetHyperParametersRequest.Size(m)
}
func (m *GetHyperParametersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHyperParametersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHyperParametersRequest proto.InternalMessageInfo

func (m *GetHyperParametersRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *GetHyperParametersRequest) GetHyperParametersId() string {
	if m != nil {
		return m.HyperParametersId
	}
	return ""
}

type GetHyperParametersResponse struct {
	ModelId              string            `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperParametersId    string            `protobuf:"bytes,2,opt,name=hyperParametersId,proto3" json:"hyperParametersId,omitempty"`
	UpgradeTo            string            `protobuf:"bytes,3,opt,name=upgradeTo,proto3" json:"upgradeTo,omitempty"`
	CanonicalCheckpoint  string            `protobuf:"bytes,4,opt,name=canonicalCheckpoint,proto3" json:"canonicalCheckpoint,omitempty"`
	HyperParameters      map[string]string `protobuf:"bytes,5,rep,name=hyperParameters,proto3" json:"hyperParameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetHyperParametersResponse) Reset()         { *m = GetHyperParametersResponse{} }
func (m *GetHyperParametersResponse) String() string { return proto.CompactTextString(m) }
func (*GetHyperParametersResponse) ProtoMessage()    {}
func (*GetHyperParametersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{16}
}

func (m *GetHyperParametersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHyperParametersResponse.Unmarshal(m, b)
}
func (m *GetHyperParametersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHyperParametersResponse.Marshal(b, m, deterministic)
}
func (m *GetHyperParametersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHyperParametersResponse.Merge(m, src)
}
func (m *GetHyperParametersResponse) XXX_Size() int {
	return xxx_messageInfo_GetHyperParametersResponse.Size(m)
}
func (m *GetHyperParametersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHyperParametersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHyperParametersResponse proto.InternalMessageInfo

func (m *GetHyperParametersResponse) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *GetHyperParametersResponse) GetHyperParametersId() string {
	if m != nil {
		return m.HyperParametersId
	}
	return ""
}

func (m *GetHyperParametersResponse) GetUpgradeTo() string {
	if m != nil {
		return m.UpgradeTo
	}
	return ""
}

func (m *GetHyperParametersResponse) GetCanonicalCheckpoint() string {
	if m != nil {
		return m.CanonicalCheckpoint
	}
	return ""
}

func (m *GetHyperParametersResponse) GetHyperParameters() map[string]string {
	if m != nil {
		return m.HyperParameters
	}
	return nil
}

type UpdateHyperParametersRequest struct {
	ModelId              string            `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperParametersId    string            `protobuf:"bytes,2,opt,name=hyperParametersId,proto3" json:"hyperParametersId,omitempty"`
	UpgradeTo            string            `protobuf:"bytes,3,opt,name=upgradeTo,proto3" json:"upgradeTo,omitempty"`
	CanonicalCheckpoint  string            `protobuf:"bytes,4,opt,name=canonicalCheckpoint,proto3" json:"canonicalCheckpoint,omitempty"`
	HyperParameters      map[string]string `protobuf:"bytes,5,rep,name=hyperParameters,proto3" json:"hyperParameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateHyperParametersRequest) Reset()         { *m = UpdateHyperParametersRequest{} }
func (m *UpdateHyperParametersRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateHyperParametersRequest) ProtoMessage()    {}
func (*UpdateHyperParametersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{17}
}

func (m *UpdateHyperParametersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHyperParametersRequest.Unmarshal(m, b)
}
func (m *UpdateHyperParametersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHyperParametersRequest.Marshal(b, m, deterministic)
}
func (m *UpdateHyperParametersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHyperParametersRequest.Merge(m, src)
}
func (m *UpdateHyperParametersRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateHyperParametersRequest.Size(m)
}
func (m *UpdateHyperParametersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHyperParametersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHyperParametersRequest proto.InternalMessageInfo

func (m *UpdateHyperParametersRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *UpdateHyperParametersRequest) GetHyperParametersId() string {
	if m != nil {
		return m.HyperParametersId
	}
	return ""
}

func (m *UpdateHyperParametersRequest) GetUpgradeTo() string {
	if m != nil {
		return m.UpgradeTo
	}
	return ""
}

func (m *UpdateHyperParametersRequest) GetCanonicalCheckpoint() string {
	if m != nil {
		return m.CanonicalCheckpoint
	}
	return ""
}

func (m *UpdateHyperParametersRequest) GetHyperParameters() map[string]string {
	if m != nil {
		return m.HyperParameters
	}
	return nil
}

type UpdateHyperParametersResponse struct {
	ModelId              string            `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperParametersId    string            `protobuf:"bytes,2,opt,name=hyperParametersId,proto3" json:"hyperParametersId,omitempty"`
	UpgradeTo            string            `protobuf:"bytes,3,opt,name=upgradeTo,proto3" json:"upgradeTo,omitempty"`
	CanonicalCheckpoint  string            `protobuf:"bytes,4,opt,name=canonicalCheckpoint,proto3" json:"canonicalCheckpoint,omitempty"`
	HyperParameters      map[string]string `protobuf:"bytes,5,rep,name=hyperParameters,proto3" json:"hyperParameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateHyperParametersResponse) Reset()         { *m = UpdateHyperParametersResponse{} }
func (m *UpdateHyperParametersResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateHyperParametersResponse) ProtoMessage()    {}
func (*UpdateHyperParametersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{18}
}

func (m *UpdateHyperParametersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHyperParametersResponse.Unmarshal(m, b)
}
func (m *UpdateHyperParametersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHyperParametersResponse.Marshal(b, m, deterministic)
}
func (m *UpdateHyperParametersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHyperParametersResponse.Merge(m, src)
}
func (m *UpdateHyperParametersResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateHyperParametersResponse.Size(m)
}
func (m *UpdateHyperParametersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHyperParametersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHyperParametersResponse proto.InternalMessageInfo

func (m *UpdateHyperParametersResponse) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *UpdateHyperParametersResponse) GetHyperParametersId() string {
	if m != nil {
		return m.HyperParametersId
	}
	return ""
}

func (m *UpdateHyperParametersResponse) GetUpgradeTo() string {
	if m != nil {
		return m.UpgradeTo
	}
	return ""
}

func (m *UpdateHyperParametersResponse) GetCanonicalCheckpoint() string {
	if m != nil {
		return m.CanonicalCheckpoint
	}
	return ""
}

func (m *UpdateHyperParametersResponse) GetHyperParameters() map[string]string {
	if m != nil {
		return m.HyperParameters
	}
	return nil
}

type ListCheckpointsRequest struct {
	ModelId              string   `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperParametersId    string   `protobuf:"bytes,2,opt,name=hyperParametersId,proto3" json:"hyperParametersId,omitempty"`
	Marker               string   `protobuf:"bytes,3,opt,name=marker,proto3" json:"marker,omitempty"`
	MaxItems             int32    `protobuf:"varint,4,opt,name=maxItems,proto3" json:"maxItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCheckpointsRequest) Reset()         { *m = ListCheckpointsRequest{} }
func (m *ListCheckpointsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCheckpointsRequest) ProtoMessage()    {}
func (*ListCheckpointsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{19}
}

func (m *ListCheckpointsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCheckpointsRequest.Unmarshal(m, b)
}
func (m *ListCheckpointsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCheckpointsRequest.Marshal(b, m, deterministic)
}
func (m *ListCheckpointsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCheckpointsRequest.Merge(m, src)
}
func (m *ListCheckpointsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCheckpointsRequest.Size(m)
}
func (m *ListCheckpointsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCheckpointsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCheckpointsRequest proto.InternalMessageInfo

func (m *ListCheckpointsRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *ListCheckpointsRequest) GetHyperParametersId() string {
	if m != nil {
		return m.HyperParametersId
	}
	return ""
}

func (m *ListCheckpointsRequest) GetMarker() string {
	if m != nil {
		return m.Marker
	}
	return ""
}

func (m *ListCheckpointsRequest) GetMaxItems() int32 {
	if m != nil {
		return m.MaxItems
	}
	return 0
}

type ListCheckpointsResponse struct {
	CheckpointIds        []string `protobuf:"bytes,1,rep,name=checkpointIds,proto3" json:"checkpointIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCheckpointsResponse) Reset()         { *m = ListCheckpointsResponse{} }
func (m *ListCheckpointsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCheckpointsResponse) ProtoMessage()    {}
func (*ListCheckpointsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{20}
}

func (m *ListCheckpointsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCheckpointsResponse.Unmarshal(m, b)
}
func (m *ListCheckpointsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCheckpointsResponse.Marshal(b, m, deterministic)
}
func (m *ListCheckpointsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCheckpointsResponse.Merge(m, src)
}
func (m *ListCheckpointsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCheckpointsResponse.Size(m)
}
func (m *ListCheckpointsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCheckpointsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCheckpointsResponse proto.InternalMessageInfo

func (m *ListCheckpointsResponse) GetCheckpointIds() []string {
	if m != nil {
		return m.CheckpointIds
	}
	return nil
}

type CreateCheckpointRequest struct {
	ModelId              string            `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperParametersId    string            `protobuf:"bytes,2,opt,name=hyperParametersId,proto3" json:"hyperParametersId,omitempty"`
	CheckpointId         string            `protobuf:"bytes,3,opt,name=checkpointId,proto3" json:"checkpointId,omitempty"`
	Link                 string            `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Info                 map[string]string `protobuf:"bytes,5,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateCheckpointRequest) Reset()         { *m = CreateCheckpointRequest{} }
func (m *CreateCheckpointRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCheckpointRequest) ProtoMessage()    {}
func (*CreateCheckpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{21}
}

func (m *CreateCheckpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCheckpointRequest.Unmarshal(m, b)
}
func (m *CreateCheckpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCheckpointRequest.Marshal(b, m, deterministic)
}
func (m *CreateCheckpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCheckpointRequest.Merge(m, src)
}
func (m *CreateCheckpointRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCheckpointRequest.Size(m)
}
func (m *CreateCheckpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCheckpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCheckpointRequest proto.InternalMessageInfo

func (m *CreateCheckpointRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *CreateCheckpointRequest) GetHyperParametersId() string {
	if m != nil {
		return m.HyperParametersId
	}
	return ""
}

func (m *CreateCheckpointRequest) GetCheckpointId() string {
	if m != nil {
		return m.CheckpointId
	}
	return ""
}

func (m *CreateCheckpointRequest) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *CreateCheckpointRequest) GetInfo() map[string]string {
	if m != nil {
		return m.Info
	}
	return nil
}

type CreateCheckpointResponse struct {
	ResourcePath         string   `protobuf:"bytes,1,opt,name=resourcePath,proto3" json:"resourcePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCheckpointResponse) Reset()         { *m = CreateCheckpointResponse{} }
func (m *CreateCheckpointResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCheckpointResponse) ProtoMessage()    {}
func (*CreateCheckpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{22}
}

func (m *CreateCheckpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCheckpointResponse.Unmarshal(m, b)
}
func (m *CreateCheckpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCheckpointResponse.Marshal(b, m, deterministic)
}
func (m *CreateCheckpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCheckpointResponse.Merge(m, src)
}
func (m *CreateCheckpointResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCheckpointResponse.Size(m)
}
func (m *CreateCheckpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCheckpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCheckpointResponse proto.InternalMessageInfo

func (m *CreateCheckpointResponse) GetResourcePath() string {
	if m != nil {
		return m.ResourcePath
	}
	return ""
}

type GetCheckpointRequest struct {
	ModelId              string   `protobuf:"bytes,1,opt,name=modelId,proto3" json:"modelId,omitempty"`
	HyperParametersId    string   `protobuf:"bytes,2,opt,name=hyperParametersId,proto3" json:"hyperParametersId,omitempty"`
	CheckpointId         string   `protobuf:"bytes,3,opt,name=checkpointId,proto3" json:"checkpointId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCheckpointRequest) Reset()         { *m = GetCheckpointRequest{} }
func (m *GetCheckpointRequest) String() string { return proto.CompactTextString(m) }
func (*GetCheckpointRequest) ProtoMessage()    {}
func (*GetCheckpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{23}
}

func (m *GetCheckpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCheckpointRequest.Unmarshal(m, b)
}
func (m *GetCheckpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCheckpointRequest.Marshal(b, m, deterministic)
}
func (m *GetCheckpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCheckpointRequest.Merge(m, src)
}
func (m *GetCheckpointRequest) XXX_Size() int {
	return xxx_messageInfo_GetCheckpointRequest.Size(m)
}
func (m *GetCheckpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCheckpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCheckpointRequest proto.InternalMessageInfo

func (m *GetCheckpointRequest) GetModelId() string {
	if m != nil {
		return m.ModelId
	}
	return ""
}

func (m *GetCheckpointRequest) GetHyperParametersId() string {
	if m != nil {
		return m.HyperParametersId
	}
	return ""
}

func (m *GetCheckpointRequest) GetCheckpointId() string {
	if m != nil {
		return m.CheckpointId
	}
	return ""
}

type GetCheckpointResponse struct {
	ResourcePath         string            `protobuf:"bytes,1,opt,name=resourcePath,proto3" json:"resourcePath,omitempty"`
	Link                 string            `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Info                 map[string]string `protobuf:"bytes,3,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetCheckpointResponse) Reset()         { *m = GetCheckpointResponse{} }
func (m *GetCheckpointResponse) String() string { return proto.CompactTextString(m) }
func (*GetCheckpointResponse) ProtoMessage()    {}
func (*GetCheckpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10d86afa5a89ec9d, []int{24}
}

func (m *GetCheckpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCheckpointResponse.Unmarshal(m, b)
}
func (m *GetCheckpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCheckpointResponse.Marshal(b, m, deterministic)
}
func (m *GetCheckpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCheckpointResponse.Merge(m, src)
}
func (m *GetCheckpointResponse) XXX_Size() int {
	return xxx_messageInfo_GetCheckpointResponse.Size(m)
}
func (m *GetCheckpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCheckpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCheckpointResponse proto.InternalMessageInfo

func (m *GetCheckpointResponse) GetResourcePath() string {
	if m != nil {
		return m.ResourcePath
	}
	return ""
}

func (m *GetCheckpointResponse) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *GetCheckpointResponse) GetInfo() map[string]string {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
	proto.RegisterType((*HealthCheckRequest)(nil), "api.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "api.HealthCheckResponse")
	proto.RegisterType((*Model)(nil), "api.Model")
	proto.RegisterType((*ListModelsRequest)(nil), "api.ListModelsRequest")
	proto.RegisterType((*ListModelsResponse)(nil), "api.ListModelsResponse")
	proto.RegisterType((*CreateModelRequest)(nil), "api.CreateModelRequest")
	proto.RegisterType((*CreateModelResponse)(nil), "api.CreateModelResponse")
	proto.RegisterType((*GetModelRequest)(nil), "api.GetModelRequest")
	proto.RegisterType((*GetModelResponse)(nil), "api.GetModelResponse")
	proto.RegisterType((*UpdateModelRequest)(nil), "api.UpdateModelRequest")
	proto.RegisterType((*UpdateModelResponse)(nil), "api.UpdateModelResponse")
	proto.RegisterType((*ListHyperParametersRequest)(nil), "api.ListHyperParametersRequest")
	proto.RegisterType((*ListHyperParametersResponse)(nil), "api.ListHyperParametersResponse")
	proto.RegisterType((*CreateHyperParametersRequest)(nil), "api.CreateHyperParametersRequest")
	proto.RegisterMapType((map[string]string)(nil), "api.CreateHyperParametersRequest.HyperParametersEntry")
	proto.RegisterType((*CreateHyperParametersResponse)(nil), "api.CreateHyperParametersResponse")
	proto.RegisterType((*GetHyperParametersRequest)(nil), "api.GetHyperParametersRequest")
	proto.RegisterType((*GetHyperParametersResponse)(nil), "api.GetHyperParametersResponse")
	proto.RegisterMapType((map[string]string)(nil), "api.GetHyperParametersResponse.HyperParametersEntry")
	proto.RegisterType((*UpdateHyperParametersRequest)(nil), "api.UpdateHyperParametersRequest")
	proto.RegisterMapType((map[string]string)(nil), "api.UpdateHyperParametersRequest.HyperParametersEntry")
	proto.RegisterType((*UpdateHyperParametersResponse)(nil), "api.UpdateHyperParametersResponse")
	proto.RegisterMapType((map[string]string)(nil), "api.UpdateHyperParametersResponse.HyperParametersEntry")
	proto.RegisterType((*ListCheckpointsRequest)(nil), "api.ListCheckpointsRequest")
	proto.RegisterType((*ListCheckpointsResponse)(nil), "api.ListCheckpointsResponse")
	proto.RegisterType((*CreateCheckpointRequest)(nil), "api.CreateCheckpointRequest")
	proto.RegisterMapType((map[string]string)(nil), "api.CreateCheckpointRequest.InfoEntry")
	proto.RegisterType((*CreateCheckpointResponse)(nil), "api.CreateCheckpointResponse")
	proto.RegisterType((*GetCheckpointRequest)(nil), "api.GetCheckpointRequest")
	proto.RegisterType((*GetCheckpointResponse)(nil), "api.GetCheckpointResponse")
	proto.RegisterMapType((map[string]string)(nil), "api.GetCheckpointResponse.InfoEntry")
}

func init() { proto.RegisterFile("repository.proto", fileDescriptor_10d86afa5a89ec9d) }

var fileDescriptor_10d86afa5a89ec9d = []byte{
	// 1177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4f, 0x6f, 0x1b, 0x55,
	0x10, 0x67, 0xd7, 0x76, 0xd2, 0x8c, 0x1b, 0xe2, 0x4e, 0xe2, 0xd8, 0xdd, 0x3a, 0x8d, 0xfb, 0x14,
	0x95, 0xa8, 0x20, 0x6f, 0x1b, 0xa2, 0xa6, 0xf8, 0x50, 0x24, 0xa2, 0xc8, 0x89, 0x4a, 0x9d, 0xe0,
	0xa4, 0x54, 0x42, 0x55, 0xc9, 0xd6, 0x7e, 0x89, 0x97, 0xd8, 0xbb, 0xcb, 0xee, 0x3a, 0x22, 0x44,
	0x11, 0x52, 0x8f, 0x1c, 0x90, 0x10, 0x9c, 0x38, 0x22, 0x71, 0x42, 0xea, 0x47, 0xe0, 0xc0, 0x57,
	0xe0, 0xc2, 0x01, 0x71, 0xe2, 0x83, 0xa0, 0x7d, 0xfb, 0xec, 0xf5, 0xfe, 0xb3, 0x6b, 0x69, 0x1b,
	0xb8, 0xf9, 0xcd, 0x7b, 0x6f, 0xe6, 0x37, 0xf3, 0x9b, 0xb7, 0x33, 0x63, 0xc8, 0x99, 0xd4, 0xd0,
	0x2d, 0xd5, 0xd6, 0xcd, 0xb3, 0x8a, 0x61, 0xea, 0xb6, 0x8e, 0x29, 0xc5, 0x50, 0xa5, 0xd2, 0xb1,
	0xae, 0x1f, 0x77, 0xa8, 0xac, 0x18, 0xaa, 0xac, 0x68, 0x9a, 0x6e, 0x2b, 0xb6, 0xaa, 0x6b, 0x96,
	0x7b, 0x84, 0x54, 0x00, 0xb7, 0xa9, 0xd2, 0xb1, 0xdb, 0x9b, 0x6d, 0xda, 0x3c, 0x69, 0xd0, 0x2f,
	0x7b, 0xd4, 0xb2, 0xb1, 0x08, 0xd3, 0x16, 0x35, 0x4f, 0xd5, 0x26, 0x2d, 0x0a, 0x65, 0x61, 0x75,
	0xa6, 0xd1, 0x5f, 0x92, 0xef, 0x05, 0x98, 0xf7, 0x5d, 0xb0, 0x0c, 0x5d, 0xb3, 0x28, 0x3e, 0x84,
	0x29, 0xcb, 0x56, 0xec, 0x9e, 0xc5, 0x2e, 0xbc, 0xbd, 0x76, 0xbb, 0xa2, 0x18, 0x6a, 0x25, 0xe2,
	0x64, 0x65, 0xdf, 0xd1, 0xa4, 0x1d, 0xef, 0xb3, 0xd3, 0x0d, 0x7e, 0x8b, 0x54, 0x61, 0xd6, 0xb7,
	0x81, 0x59, 0x98, 0x7e, 0x52, 0x7f, 0x54, 0xdf, 0x7d, 0x5a, 0xcf, 0xbd, 0xe5, 0x2c, 0xf6, 0xb7,
	0x1a, 0x9f, 0xee, 0xd4, 0x6b, 0x39, 0x01, 0xe7, 0x20, 0x5b, 0xdf, 0x3d, 0xf8, 0xbc, 0x2f, 0x10,
	0xc9, 0x37, 0x90, 0x79, 0xac, 0xb7, 0x68, 0xc7, 0x81, 0xdd, 0x75, 0x7e, 0xec, 0xb4, 0xfa, 0xb0,
	0xf9, 0x12, 0xcb, 0x90, 0x6d, 0x51, 0xab, 0x69, 0xaa, 0x86, 0xe3, 0x7c, 0x51, 0x64, 0xbb, 0xc3,
	0x22, 0xac, 0x42, 0xb1, 0xa9, 0x68, 0xba, 0xa6, 0x36, 0x95, 0xce, 0xf6, 0x99, 0x41, 0xcd, 0x3d,
	0xc5, 0x54, 0xba, 0xd4, 0xa6, 0xa6, 0x55, 0x4c, 0xb1, 0xe3, 0xb1, 0xfb, 0xa4, 0x06, 0xd7, 0x3e,
	0x56, 0x2d, 0x9b, 0x81, 0xb0, 0xfa, 0x31, 0x5c, 0x84, 0xa9, 0xae, 0x62, 0x9e, 0x50, 0x93, 0x63,
	0xe1, 0x2b, 0x94, 0xe0, 0x4a, 0x57, 0xf9, 0x6a, 0xc7, 0xa6, 0x5d, 0x8b, 0xe1, 0xc8, 0x34, 0x06,
	0x6b, 0x72, 0x17, 0x70, 0x58, 0x11, 0x8f, 0xad, 0x73, 0xc3, 0xf5, 0xc3, 0x89, 0x6e, 0x6a, 0x75,
	0xa6, 0x31, 0x58, 0x93, 0xfb, 0x80, 0x9b, 0x26, 0x55, 0x6c, 0xca, 0xee, 0xf4, 0x6d, 0x97, 0x21,
	0xc3, 0x4e, 0x30, 0xd3, 0xd9, 0x35, 0x60, 0x64, 0xb8, 0x27, 0xdc, 0x0d, 0xf2, 0x01, 0xcc, 0xfb,
	0xee, 0x71, 0x53, 0x04, 0xae, 0x9a, 0xd4, 0xd2, 0x7b, 0x66, 0x93, 0xee, 0x29, 0x76, 0x9b, 0x43,
	0xf7, 0xc9, 0xc8, 0xbb, 0x30, 0x57, 0xa3, 0xb6, 0xcf, 0x5e, 0x6c, 0xe0, 0xc9, 0x3a, 0xe4, 0xbc,
	0xc3, 0xdc, 0xc8, 0x78, 0x74, 0x7b, 0x80, 0x4f, 0x8c, 0x56, 0xd0, 0xab, 0x51, 0xf4, 0x72, 0x8d,
	0x62, 0x9c, 0xc6, 0x0d, 0x98, 0xf7, 0x69, 0x7c, 0x6d, 0x28, 0x5f, 0x80, 0xe4, 0x50, 0x12, 0xa0,
	0x7c, 0x3c, 0x24, 0x8f, 0x7e, 0x31, 0x96, 0xfe, 0x54, 0x80, 0xfe, 0xc7, 0x70, 0x23, 0xd2, 0x16,
	0x07, 0x5b, 0x01, 0x6c, 0xfb, 0xb7, 0xbc, 0x8c, 0x88, 0xd8, 0x21, 0xbf, 0x89, 0x50, 0x72, 0x49,
	0x9e, 0x18, 0xfd, 0x7b, 0x70, 0x2d, 0xa4, 0x90, 0x3b, 0x12, 0xde, 0xc0, 0xbb, 0x30, 0x3f, 0x78,
	0x1b, 0xec, 0xb1, 0x1b, 0xba, 0xaa, 0xd9, 0xfc, 0xd9, 0x44, 0x6d, 0xe1, 0x21, 0xcc, 0x05, 0xd4,
	0x14, 0xd3, 0xe5, 0xd4, 0x6a, 0x76, 0xed, 0x3e, 0x63, 0x60, 0x14, 0xea, 0x4a, 0x40, 0xbc, 0xa5,
	0xd9, 0xe6, 0x59, 0x23, 0xa8, 0x4e, 0xfa, 0x08, 0x16, 0xa2, 0x0e, 0x62, 0x0e, 0x52, 0x27, 0xf4,
	0x8c, 0xfb, 0xeb, 0xfc, 0xc4, 0x05, 0xc8, 0x9c, 0x2a, 0x9d, 0x1e, 0xe5, 0xfe, 0xb9, 0x8b, 0xaa,
	0xf8, 0x40, 0x20, 0x9b, 0xb0, 0x14, 0x83, 0x64, 0x82, 0xe7, 0xd2, 0x84, 0xeb, 0x35, 0x6a, 0xbf,
	0x59, 0x06, 0xc8, 0x9f, 0x22, 0x48, 0x51, 0x56, 0x38, 0xce, 0xa4, 0x88, 0x2e, 0xc1, 0x4c, 0xcf,
	0x38, 0x36, 0x95, 0x16, 0x3d, 0xd0, 0x39, 0xbd, 0x9e, 0x20, 0x2e, 0x0d, 0xd2, 0xf1, 0x69, 0xf0,
	0x3c, 0x9c, 0x06, 0x19, 0x96, 0x06, 0xeb, 0x2c, 0x0d, 0xe2, 0x3d, 0xba, 0xc4, 0x24, 0xf8, 0x4b,
	0x84, 0x92, 0xfb, 0xe9, 0x78, 0xc3, 0xaf, 0x28, 0xe9, 0xe0, 0x1e, 0xc6, 0x05, 0xd7, 0x7d, 0x63,
	0xa3, 0x7c, 0xba, 0xc4, 0xf0, 0xfe, 0x2d, 0xc2, 0x52, 0x0c, 0x94, 0xff, 0x79, 0xf2, 0x2a, 0x71,
	0xf1, 0xdd, 0x18, 0x15, 0xdf, 0x4b, 0xcf, 0xdf, 0x1f, 0x05, 0x58, 0x74, 0xaa, 0x8a, 0x87, 0x3c,
	0xf1, 0xcc, 0xf5, 0x6a, 0x5d, 0x2a, 0xb6, 0xd6, 0xa5, 0x03, 0xb5, 0xee, 0x43, 0x28, 0x84, 0x50,
	0x71, 0xc2, 0x57, 0x60, 0xb6, 0x39, 0x10, 0x7b, 0x25, 0xce, 0x2f, 0x24, 0xdf, 0x89, 0x50, 0x70,
	0xbf, 0xce, 0x9e, 0x8e, 0xa4, 0x1d, 0x23, 0x70, 0x75, 0xd8, 0x28, 0x77, 0xcf, 0x27, 0x43, 0x84,
	0x74, 0x47, 0xd5, 0x4e, 0x78, 0xa6, 0xb0, 0xdf, 0x58, 0x85, 0xb4, 0xaa, 0x1d, 0xe9, 0x3c, 0x1f,
	0x6e, 0x0f, 0xd5, 0xb4, 0x10, 0xd6, 0xca, 0x8e, 0x76, 0xa4, 0xbb, 0xf4, 0xb3, 0x3b, 0xd2, 0x06,
	0xcc, 0x0c, 0x44, 0x13, 0x11, 0xfd, 0x10, 0x8a, 0x61, 0x1b, 0x13, 0x14, 0xaa, 0x97, 0x02, 0x2c,
	0xd4, 0xa8, 0xfd, 0x9f, 0x46, 0x93, 0xfc, 0x2e, 0x40, 0x3e, 0x00, 0xe2, 0xf5, 0x5d, 0x18, 0x70,
	0x21, 0x0e, 0x71, 0xf1, 0x80, 0x73, 0x91, 0x62, 0x5c, 0xac, 0xf4, 0x0b, 0x4b, 0xd8, 0x42, 0x62,
	0x4c, 0xac, 0x7d, 0x3b, 0x0b, 0xd0, 0x18, 0x0c, 0x63, 0xf8, 0x0c, 0xa6, 0xdd, 0x41, 0xe8, 0x6b,
	0x2c, 0x84, 0xc7, 0x22, 0x16, 0x63, 0xa9, 0x18, 0x37, 0x2f, 0x91, 0x9b, 0x2f, 0xff, 0xf8, 0xe7,
	0x07, 0xb1, 0x88, 0x8b, 0xf2, 0xe9, 0x3d, 0xd9, 0x1b, 0xf1, 0xe4, 0x36, 0x57, 0xf9, 0x0c, 0xc0,
	0x9b, 0x19, 0x70, 0x91, 0xe9, 0x09, 0x4d, 0x23, 0x52, 0x21, 0x24, 0xe7, 0xea, 0x97, 0x98, 0xfa,
	0x02, 0xe6, 0x03, 0xea, 0xbb, 0xae, 0xbe, 0x17, 0x90, 0x1d, 0x9a, 0x13, 0x38, 0xfe, 0xf0, 0xc4,
	0xc1, 0xf1, 0x47, 0x8c, 0x14, 0xa4, 0xcc, 0x0c, 0x48, 0x24, 0xda, 0x40, 0x55, 0xb8, 0x83, 0x87,
	0x70, 0xa5, 0x3f, 0x23, 0xe0, 0x42, 0x9f, 0x1f, 0x9f, 0xf6, 0x7c, 0x40, 0xca, 0x55, 0xbf, 0xc3,
	0x54, 0xdf, 0xc2, 0xe5, 0x48, 0xd5, 0xf2, 0x39, 0x4f, 0xd3, 0x0b, 0xec, 0x40, 0x76, 0xa8, 0xfb,
	0xe7, 0x5e, 0x84, 0x27, 0x0c, 0xee, 0x45, 0xc4, 0xa0, 0x40, 0xee, 0x30, 0x53, 0x2b, 0xd2, 0x38,
	0x53, 0x8e, 0x3f, 0xce, 0x8c, 0x1c, 0xd1, 0xc7, 0xe3, 0xf2, 0x80, 0x83, 0xe8, 0xaa, 0x2b, 0x95,
	0xe3, 0x0f, 0x70, 0x18, 0x1b, 0x0c, 0xc6, 0x3d, 0x94, 0xc7, 0xc0, 0x90, 0xd9, 0xeb, 0x33, 0x3c,
	0xdb, 0x3f, 0x09, 0x90, 0x8f, 0xec, 0x65, 0xf1, 0xd6, 0xd8, 0x8e, 0x5b, 0x22, 0xa3, 0x8e, 0x70,
	0x64, 0x55, 0x86, 0x6c, 0x9d, 0x4c, 0x8a, 0xcc, 0x09, 0xd8, 0xcf, 0x02, 0x60, 0xb8, 0xd7, 0xc3,
	0x9b, 0xb1, 0x4d, 0xa0, 0x0b, 0x6b, 0x79, 0x4c, 0x93, 0x48, 0x1e, 0x31, 0x4c, 0x5b, 0xb8, 0x39,
	0x21, 0x26, 0xf9, 0x3c, 0xf4, 0xf1, 0xba, 0xc0, 0x57, 0x02, 0xe4, 0x23, 0x6b, 0x3a, 0x8f, 0xe0,
	0xa8, 0x7e, 0x8a, 0x47, 0x70, 0x64, 0x4b, 0x40, 0xea, 0x0c, 0xed, 0xb6, 0x94, 0x04, 0x5a, 0x27,
	0xaa, 0xbf, 0x08, 0x30, 0x17, 0x28, 0xb1, 0x78, 0x63, 0x90, 0x61, 0xe1, 0x76, 0x40, 0x2a, 0x45,
	0x6f, 0x72, 0x78, 0x4f, 0x19, 0xbc, 0x4f, 0x70, 0x37, 0x01, 0x78, 0x72, 0x73, 0x08, 0xd3, 0xaf,
	0x02, 0xe4, 0x82, 0x85, 0x0b, 0x4b, 0xa3, 0x6a, 0xa6, 0xb4, 0x14, 0xb3, 0xcb, 0xa1, 0x7e, 0xc6,
	0xa0, 0x1e, 0x90, 0xa4, 0xa1, 0x3a, 0x51, 0x7d, 0x25, 0xc0, 0xac, 0xaf, 0x7c, 0xe0, 0xf5, 0xa8,
	0x92, 0xe2, 0xe2, 0x94, 0xe2, 0xab, 0x0d, 0x39, 0x62, 0x20, 0x0f, 0xf1, 0x79, 0xc2, 0x20, 0xe5,
	0xf3, 0xe1, 0x82, 0x7a, 0xf1, 0x62, 0x8a, 0xfd, 0xd1, 0xf7, 0xfe, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x8e, 0x1f, 0x52, 0xa3, 0x1f, 0x14, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RepositoryClient is the client API for Repository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RepositoryClient interface {
	Healthz(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error)
	GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error)
	UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*UpdateModelResponse, error)
	ListHyperParameters(ctx context.Context, in *ListHyperParametersRequest, opts ...grpc.CallOption) (*ListHyperParametersResponse, error)
	CreateHyperParameters(ctx context.Context, in *CreateHyperParametersRequest, opts ...grpc.CallOption) (*CreateHyperParametersResponse, error)
	GetHyperParameters(ctx context.Context, in *GetHyperParametersRequest, opts ...grpc.CallOption) (*GetHyperParametersResponse, error)
	UpdateHyperParameters(ctx context.Context, in *UpdateHyperParametersRequest, opts ...grpc.CallOption) (*UpdateHyperParametersResponse, error)
	ListCheckpoints(ctx context.Context, in *ListCheckpointsRequest, opts ...grpc.CallOption) (*ListCheckpointsResponse, error)
	CreateCheckpoint(ctx context.Context, in *CreateCheckpointRequest, opts ...grpc.CallOption) (*CreateCheckpointResponse, error)
	GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error)
}

type repositoryClient struct {
	cc *grpc.ClientConn
}

func NewRepositoryClient(cc *grpc.ClientConn) RepositoryClient {
	return &repositoryClient{cc}
}

func (c *repositoryClient) Healthz(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/api.Repository/Healthz", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, "/api.Repository/ListModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error) {
	out := new(CreateModelResponse)
	err := c.cc.Invoke(ctx, "/api.Repository/CreateModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error) {
	out := new(GetModelResponse)
	err := c.cc.Invoke(ctx, "/api.Repository/GetModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*UpdateModelResponse, error) {
	out := new(UpdateModelResponse)
	err := c.cc.Invoke(ctx, "/api.Repository/UpdateModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) ListHyperParameters(ctx context.Context, in *ListHyperParametersRequest, opts ...grpc.CallOption) (*ListHyperParametersResponse, error) {
	out := new(ListHyperParametersResponse)
	err := c.cc.Invoke(ctx, "/api.Repository/ListHyperParameters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) CreateHyperParameters(ctx context.Context, in *CreateHyperParametersRequest, opts ...grpc.CallOption) (*CreateHyperParametersResponse, error) {
	out := new(CreateHyperParametersResponse)
	err := c.cc.Invoke(ctx, "/api.Repository/CreateHyperParameters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) GetHyperParameters(ctx context.Context, in *GetHyperParametersRequest, opts ...grpc.CallOption) (*GetHyperParametersResponse, error) {
	out := new(GetHyperParametersResponse)
	err := c.cc.Invoke(ctx, "/api.Repository/GetHyperParameters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) UpdateHyperParameters(ctx context.Context, in *UpdateHyperParametersRequest, opts ...grpc.CallOption) (*UpdateHyperParametersResponse, error) {
	out := new(UpdateHyperParametersResponse)
	err := c.cc.Invoke(ctx, "/api.Repository/UpdateHyperParameters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) ListCheckpoints(ctx context.Context, in *ListCheckpointsRequest, opts ...grpc.CallOption) (*ListCheckpointsResponse, error) {
	out := new(ListCheckpointsResponse)
	err := c.cc.Invoke(ctx, "/api.Repository/ListCheckpoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) CreateCheckpoint(ctx context.Context, in *CreateCheckpointRequest, opts ...grpc.CallOption) (*CreateCheckpointResponse, error) {
	out := new(CreateCheckpointResponse)
	err := c.cc.Invoke(ctx, "/api.Repository/CreateCheckpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error) {
	out := new(GetCheckpointResponse)
	err := c.cc.Invoke(ctx, "/api.Repository/GetCheckpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoryServer is the server API for Repository service.
type RepositoryServer interface {
	Healthz(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error)
	GetModel(context.Context, *GetModelRequest) (*GetModelResponse, error)
	UpdateModel(context.Context, *UpdateModelRequest) (*UpdateModelResponse, error)
	ListHyperParameters(context.Context, *ListHyperParametersRequest) (*ListHyperParametersResponse, error)
	CreateHyperParameters(context.Context, *CreateHyperParametersRequest) (*CreateHyperParametersResponse, error)
	GetHyperParameters(context.Context, *GetHyperParametersRequest) (*GetHyperParametersResponse, error)
	UpdateHyperParameters(context.Context, *UpdateHyperParametersRequest) (*UpdateHyperParametersResponse, error)
	ListCheckpoints(context.Context, *ListCheckpointsRequest) (*ListCheckpointsResponse, error)
	CreateCheckpoint(context.Context, *CreateCheckpointRequest) (*CreateCheckpointResponse, error)
	GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error)
}

func RegisterRepositoryServer(s *grpc.Server, srv RepositoryServer) {
	s.RegisterService(&_Repository_serviceDesc, srv)
}

func _Repository_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Repository/Healthz",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).Healthz(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Repository/ListModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Repository/CreateModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).CreateModel(ctx, req.(*CreateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Repository/GetModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).GetModel(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_UpdateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).UpdateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Repository/UpdateModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).UpdateModel(ctx, req.(*UpdateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_ListHyperParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHyperParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).ListHyperParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Repository/ListHyperParameters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).ListHyperParameters(ctx, req.(*ListHyperParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_CreateHyperParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHyperParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).CreateHyperParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Repository/CreateHyperParameters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).CreateHyperParameters(ctx, req.(*CreateHyperParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_GetHyperParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHyperParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).GetHyperParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Repository/GetHyperParameters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).GetHyperParameters(ctx, req.(*GetHyperParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_UpdateHyperParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHyperParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).UpdateHyperParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Repository/UpdateHyperParameters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).UpdateHyperParameters(ctx, req.(*UpdateHyperParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_ListCheckpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCheckpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).ListCheckpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Repository/ListCheckpoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).ListCheckpoints(ctx, req.(*ListCheckpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_CreateCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).CreateCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Repository/CreateCheckpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).CreateCheckpoint(ctx, req.(*CreateCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_GetCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).GetCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Repository/GetCheckpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).GetCheckpoint(ctx, req.(*GetCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Repository_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Repository",
	HandlerType: (*RepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _Repository_Healthz_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _Repository_ListModels_Handler,
		},
		{
			MethodName: "CreateModel",
			Handler:    _Repository_CreateModel_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _Repository_GetModel_Handler,
		},
		{
			MethodName: "UpdateModel",
			Handler:    _Repository_UpdateModel_Handler,
		},
		{
			MethodName: "ListHyperParameters",
			Handler:    _Repository_ListHyperParameters_Handler,
		},
		{
			MethodName: "CreateHyperParameters",
			Handler:    _Repository_CreateHyperParameters_Handler,
		},
		{
			MethodName: "GetHyperParameters",
			Handler:    _Repository_GetHyperParameters_Handler,
		},
		{
			MethodName: "UpdateHyperParameters",
			Handler:    _Repository_UpdateHyperParameters_Handler,
		},
		{
			MethodName: "ListCheckpoints",
			Handler:    _Repository_ListCheckpoints_Handler,
		},
		{
			MethodName: "CreateCheckpoint",
			Handler:    _Repository_CreateCheckpoint_Handler,
		},
		{
			MethodName: "GetCheckpoint",
			Handler:    _Repository_GetCheckpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repository.proto",
}
